<?php
include "header.phtml";
?>
<body>
  <div class="about-row">
    <div class="row">
      <div class="col-md-12 inner-about-row">
        <h1>About Us</h1>
        <h3>How do we help? Please let us know your problem</h3>
      </div>
    </div>
  
  </div>
 
<section class="about" id="about">
<div class="container h-100">
  <div class="row h-100 justify-content-center align-items-center">
    <div class="col-8">
         <div class="title text-center">
                            <h1 class= "animated slideInDown" style="animation-delay: 1s">About Us</h1>
                            <div class="border"></div>
                        </div>
         <div class="title text-center" >
         <p>
                         This is the last online examination system you will ever need! With our easy online exam builder you will set up your own engaging exams that fit any kind of difficulty level. Build and create your online exams & tests with great ease and provide your users with appropriate feedback, so they will have a rich learning experience.
                        </p>    
        </div>
      
    </div>
      <div class="col-4" style="margin: 0;">
      <div >

<img src="img/2.jpeg"  style="width:100%; height:100%;"/>

 </div>
      
      </div>
  </div>
</div>
    </section>



<section class="services" id="services">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-4 s_item text-center">
                    <div class="s_icon">
                        <i class="fa fa-car"></i>
                    </div>
                    <h3>WHO WE ARE ?</h3>
                    <p>Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme.</p>
                </div>
                <div class="col-xs-12 col-sm-4 s_item text-center">
                    <div class="s_icon">
                        <i class="fa fa-truck"></i>
                    </div>
                    <h3>WHAT WE DO ?</h3>
                    <p>Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme.</p>
                </div>
                <div class="col-xs-12 col-sm-4 s_item text-center">
                    <div class="s_icon">
                        <i class="fa fa-cog"></i>
                    </div>
                    <h3>OUR SERVICES</h3>
                    <p>Themes and styles also help keep your document coordinated. When you click Design and choose a new Theme, the pictures, charts, and SmartArt graphics change to match your new theme. When you apply styles, your headings change to match the new theme. </p>
                </div>
            </div>
        </div>
    </section>










        <section class="our-team-section">
        <div class="container">
             <div class="title text-center">
                            <h1 class= "animated slideInDown" style="animation-delay: 1s">Our Team</h1>
                            <div class="border"></div>
                        </div>
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                   
                    <div class="our-team">
                        <div class="pic">
                            <img src="img/p1.png">
                        </div>
                        <div class="team-content">
                            <h3 class="title">Blqeise</h3>
                            <span class="post">Student Of Coding Academy</span>
                        </div>
                        <ul class="social">
                            <li>
                                <a href="#"  target="_blank"class="fa fa-facebook"></a>
                            </li>
                            <li>
                                <a href="#" class="fa fa-twitter"></a>
                            </li>
                            <li>
                                <a href="#" class="fa fa-google-plus"></a>
                            </li>
                            <li>
                                <a href="#" class="fa fa-linkedin"></a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="our-team">
                        <div class="pic">
                            <img src="img/p2.png">
                        </div>
                        <div class="team-content">
                            <h3 class="title">kalood</h3>
                            <span class="post">Student Of Coding Academy</span>
                        </div>
                        <ul class="social">
                            <li>
                                <a href="#" class="fa fa-facebook"></a>
                            </li>
                            <li>
                                <a href="#" class="fa fa-twitter"></a>
                            </li>
                            <li>
                                <a href="#" class="fa fa-google-plus"></a>
                            </li>
                            <li>
                                <a href="#" class="fa fa-linkedin"></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="our-team">
                        <div class="pic">
                            <img src="img/p3.png">
                        </div>
                        <div class="team-content">
                            <h3 class="title">Refat</h3>
                            <span class="post">Student Of Coding Academy </span>
                        </div>
                        <ul class="social">
                            <li>
                                <a href="#" class="fa fa-facebook"></a>
                            </li>
                            <li>
                                <a href="#" class="fa fa-twitter"></a>
                            </li>
                            <li>
                                <a href="#" class="fa fa-google-plus"></a>
                            </li>
                            <li>
                                <a href="#" class="fa fa-linkedin"></a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="our-team">
                        <div class="pic">
                            <img src="img/p3.png">
                        </div>
                        <div class="team-content">
                            <h3 class="title">Moheamd</h3>
                            <span class="post">Student Of Coding Academy </span>
                        </div>
                        <ul class="social">
                            <li>
                                <a href="#" class="fa fa-facebook"></a>
                            </li>
                            <li>
                                <a href="#" class="fa fa-twitter"></a>
                            </li>
                            <li>
                                <a href="#" class="fa fa-google-plus"></a>
                            </li>
                            <li>
                                <a href="#" class="fa fa-linkedin"></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        </section>


      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>
    <script src="js/main.js"></script>
       <script>
    window.addEventListener("scroll",function(){
    let backnavbar =document.getElementById('navbar-area');
        
        if(window.pageYOffset > 0){
            backnavbar.classList.add("cus-nav");
        }else{
            backnavbar.classList.remove("cus-nav")
        }
    });
    </script>

<?php
include "footer.phtml";
?>