<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Q</title>
</head>


<body>




<!--////////////////////////////////////////////////////////////////////////////////////////////////////////////-->
<div class="container">
<h2>add q </h2>

<?php

echo '
<div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
        <form class="form_exam" id="form_exam" method="POST">
         <div class="row">
                    <div class="col-md-12">
                        <div class="div_name"><h5> insert Quewstions</h5></div>
                    </div>
                    <div class="col-md-12">
                     '.Message::check('quez Degree').'
                    </div>  
                </div>
            <fieldset>
                
                ';
                $n=$_SESSION['number_que'];

                for($i=1;$i<=$n;$i++)
                {
                echo '<b>Question number&nbsp;'.$i.'&nbsp;:</><br /><!-- Text input-->
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label" for="qns'.$i.' "></label>
                    <div class="col-sm-11">
                        <textarea rows="3" cols="5" name="qns'.$i.'" class="form-control" placeholder="Write question number '.$i.' here..."></textarea>
                    </div>
                </div>
                    '.Message::check("qns$i").'
                <!-- Text input-->
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label" for="time"></label>
                    <div class="col-sm-11">
                        <input id="q_degree" name="q_degree'.$i.'" placeholder="Enter degree of Question " class="form-control input-md" min="1" type="number">
                    </div>
                    '.Message::check("q_degree$i").'
                </div>

                <!-- Text input-->
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label" for="'.$i.'1"></label>
                    <div class="col-sm-11">
                        <input id="'.$i.'1" name="'.$i.'1" placeholder="Enter option a" class="form-control input-md" type="text">
                    </div>
                    '.Message::check("$i"."1").'
                </div>
                <!-- Text input-->
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label" for="'.$i.'2"></label>
                    <div class="col-sm-11">
                        <input id="'.$i.'2" name="'.$i.'2" placeholder="Enter option b" class="form-control input-md" type="text">
                    </div>
                    '.Message::check("$i"."2").'
                </div>
                <!-- Text input-->
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label" for="'.$i.'3"></label>
                    <div class="col-sm-11">
                        <input id="'.$i.'3" name="'.$i.'3" placeholder="Enter option c" class="form-control input-md" type="text">
                    </div>
                    '.Message::check("$i"."3").'
                </div>
                <!-- Text input-->
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label" for="'.$i.'4"></label>
                    <div class="col-sm-11">
                        <input id="'.$i.'4" name="'.$i.'4" placeholder="Enter option d" class="form-control input-md" type="text">
                    </div>
                    '.Message::check("$i"."4").'
                </div>
                <br />
                 <div class="form-group row">
                 <label class="col-sm-12 col-form-label" for="">Correct answe for question '.$i.'r</label>
                  <label class="col-sm-1 col-form-label" ></label>
                  <div class="col-sm-11">
                <select id="ans'.$i.'" name="ans'.$i.'" placeholder="Choose correct answer " class="form-control input-md" >
                    <option value="a" selected>option a</option>
                    <option value="b">option b</option>
                    <option value="c">option c</option>
                    <option value="d">option d</option> 
                    </select> 
                    </div>
                    </div>
                    <br /><br />';
                }

                echo '  <div class="form-group row">
                 <label class="col-sm-1 col-form-label" for=""></label>
                  <div class="col-sm-11">
                        <input type="submit" class="form-control btn btn-outline-success" name="next"  value="next"></input>
                  </div>
                  </div> 
                   <div class="form-group row">
                 <label class="col-sm-1 col-form-label" for=""></label>
                  <div class="col-sm-11">
                    <input type="submit" class="form-control btn btn-outline-primary"  name="save" value="save"></input>                      
                  </div>
                </div>
            </fieldset>
        </form>
        </div>
   ';

                ?>

</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>

<script>
    /************************************************************************/
    $(document).ready(function(){
        $(".new").click(function(){
            $("#phoneArea").append('  <li>\n' +
                '                                <div class="input-group">\n' +
                '                                <div class="input-group-prepend">\n' +

                '                                  </div>\n' +
                '                                    <input  class=" form-control" id="phone" type="text">\n' +
                '                                </div>\n' +
                '                            </li>');
        });



        $('form[id="form_exam"]').validate({
            rules: {
                qcontent: 'required'

            },
            messages: {
                qcontent: 'This field is required'

            },
            submitHandler: function(form) {
                form.submit();
            }
        });

    });

</script>
</body>
</html>