<?php
include "header.phtml";
?>
    <div class="container-fluid no-padding">
  
  <div class="about-row">
    <div class="row">
      <div class="col-md-12 inner-about-row">
        <h1>Contact Us</h1>
        <h3>How do we help? Please let us know your problem</h3>
      </div>
    </div>
  
  </div>
 

<div class="contact">

  <div class="contact-title">
    <h1>Contact Form</h1>
  </div>

  <!-- form -->
  <div class="form-container">

    <form class="form">
      <div class="form-name">
        <input type="text" id="name" name="name" placeholder="Name" required="">
      </div>
      <div class="form-email">
        <input type="email" id="email" name="email" placeholder="Email" required="">
      </div>
      <div class="form-message">
        <textarea id="message" name="message" placeholder="Message" required=""></textarea>
      </div>
      <div class="center-align">
        <a href="#">submit</a>
      </div>
    </form>

  </div>
</div>






    
    
           <footer class="site-footer">
     
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by 
         <a href="#">Ability lab</a>.
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>   
            </ul>
          </div>
        </div>
      </div>
</footer>
    
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>
    <script src="/js/main.js"></script>
       <script>
    window.addEventListener("scroll",function(){
    let backnavbar =document.getElementById('navbar-area');
        
        if(window.pageYOffset > 0){
            backnavbar.classList.add("cus-nav");
        }else{
            backnavbar.classList.remove("cus-nav")
        }
    });
    </script>

<?php
include "footer.phtml";
?>