<!DOCTYPE html>
<?php
include "header.phtml";
?>
<html>
<head>

    <title>Exam Details</title>
</head>


<div id="time" ></div>
<div class="container">


    <table class="table" style="width:100%; border-spacing: 5px;">
        <tr>
            <td><h4>Exam_id</h4></td>
            <td><h4>Samples</h4></td>
            <td><h4>Dismit Exam</h4></td>



        </tr>
        <?php
        foreach($this->view_data['ex_exams'] as $row ){
            $ex_id =$row['exam_id'];
            ?>
            <tr>
<!--            <td>--><?php //echo $ex_id ?><!--</td>-->
            <td><a href="/exam/top_members_one_exam/<?php echo $ex_id ?>"><?php echo $row['exam_name'] ?></a></td>
                <td>
                   <ul>
                <?php
        foreach($this->view_data['samples_ex'] as $s ){
            foreach ($s as $sam){
                if($ex_id==$sam['exam_id']){
            ?>
                <li><?php echo $sam['sample_name'] ?></li>

        <?php }}}
        echo "</ul></td>";
      ?>
                       <td><a href="/exam/dismit_exam/<?php echo $sam['exam_id'] ?>">Dismit exam</a></td>

                       <?php
            echo"</tr>";
        } ?>


    </table>

</div>


</body>
</html>