<?php include VIEW . "header.phtml" ?>
<style>
    .error-page{
        background: #ececec;
        width: 100%;
        height: 100%;
        font-family: Arial;
        text-align: center;
        padding:8% 0 ;
    }
    .error-page p{
        font-weight: bolder;
        font-size: 28px;
        color:#37b2b5 ;
        margin:0 auto;
        padding: 0;
    }
    .error-btn{
        width: 25%;
        background-color:#37b2b5;
        border:#37b2b5;
    }

    .error-btn:hover{
        background: #2f9598;
        color: #fff;
    }

    .error-img{
        width: 12%;
        margin: 0 auto;
    }
</style>
<div class="error-page">
    <div class="container-fluid">
        <img src="/images/notfound.svg" class="error-img">
        <p>Oops...!</p>
        <p>NOT FOUND 404</p>
        <a  href="/home/index" class="btn btn-secondary btn-lg error-btn" role="button" aria-pressed="true">HOME</a>
    </div>
</div>
