<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <title>Ability lab</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Cairo:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.css">
   
</head>

<body>

    <nav class="navbar fixed-top navbar-expand-lg navbar-light fixed-top " id="navbar-area" >
        <div class="container">
               <img src="img/logo.png" width="79px" style="height: 50px;margin: 9px;background-color: #fff;" class="rounded-circle">
        <a class="navbar-brand" href="#"> Ablity Lab</a>
         
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="exam.phtml">Exam</a>
            </li>
               <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
               <li class="nav-item">
              <a class="nav-link" href="about.phtml">About Us</a>
            </li>
               <li class="nav-item">
              <a class="nav-link" href="contact.phtml">Contact Us</a>
            </li>
              <li class="nav-item">
              <a class="nav-link" href="faq.phtml">FAQs</a>
            </li>
<!--
   
--></ul>
            <form class="form-inline my-2 my-lg-0">
    
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#SIGNIN">
  SIGNIN
</button>
    </form>
  
            </div>
        </div>
      </nav>
    <!-------------------------------------START Modal SIGN IP----------------------------------------->
    <div class="modal fade" id="SIGNIN" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
       <div class="contact">
  <div class="contact-title">
    <h1>LOGIN</h1>
  </div>

  <!-- form -->
  <div class="form-container">

    <form class="form">
      <div class="form-name">
        <input type="text" id="name" name="name" placeholder="Name" required="">
      </div>
      <div class="form-email">
        <input type="email" id="email" name="email" placeholder="Email" required="">
      </div>
     
      <div class="center-align" id="one">
        <a href="#">SEND</a>
          <a href="#" data-toggle="modal" data-target="#SIGNUP">SIGN UP</a>
          
      </div>
      <div class="center-align">
           <a  id="forget" href="#"data-toggle="modal" data-target="#FORGET" id="two">forget password</a>
        </div>
        
    </form>

  </div>
</div>
      </div>
     
    </div>
  </div>
</div>
 <!-------------------------------------END Modal SIGN IN----------------------------------------->    
<!-------------------------------------START Modal SIGN UP----------------------------------------->
     <div class="modal fade" id="SIGNUP" tabindex="-1" role="dialog" aria-labelledby="SIGNUP" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    
      <div class="modal-body">
       <div class="contact">

  <div class="contact-title">
    <h1>REGISTER</h1>
  </div>

  <!-- form -->
  <div class="form-container">

    <form class="form">
      <div class="form-name">
        <input type="text" id="name" name="name" placeholder="Name" required="">
      </div>
      <div class="form-email">
        <input type="email" id="email" name="email" placeholder="Email" required="">
      </div>
        <div class="form-email">
            
        <input type="email" id="email" name="email" placeholder="Email" required="">
      </div>
        <div class="form-email">
        <input type="email" id="email" name="email" placeholder="Email" required="">
      </div>
        <div class="form-email">
        <input type="email" id="email" name="email" placeholder="Email" required="">
      </div>
        <div class="form-email">
        <input type="email" id="email" name="email" placeholder="Email" required="">
      </div>
        <div class="form-email">
        <input type="email" id="email" name="email" placeholder="Email" required="">
      </div>
     
      <div class="center-align" id="three">
        <a href="#" data-toggle="modal" data-target="#SIGNIN">SIGN IN</a>

          <a href="#" >SEND</a>
      </div>
      
        
    </form>

  </div>
</div>
      </div>
     
    </div>
  </div>
</div>
 <!-------------------------------------END Modal SIGN UP----------------------------------------->    
<!-------------------------------------START Modal FORGET----------------------------------------->
     <div class="modal fade" id="FORGET" tabindex="-1" role="dialog" aria-labelledby="FORGET" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    
      <div class="modal-body">
       <div class="contact">

  <div class="contact-title">
    <h1>FORGET PASSWORD</h1>
  </div>

  <!-- form -->
  <div class="form-container">

    <form class="form">
      
      <div class="form-email">
        <input type="email" id="email" name="email" placeholder="Email" required="">
      </div>
     
      <div class="center-align">
        

          <a href="#" >SEND</a>
      </div>
     
        
    </form>

  </div>
</div>
      </div>
     
    </div>
  </div>
</div>
<!-----------------------------------END Modal FORGET------------------------------------------->
     <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="img/1.jpeg" class="d-block w-100" alt="...">
         <div class="carousel-caption d-none d-md-block">
                <h5 class= "animated bounceInRight" style="animation-delay: 1s">Second slide label</h5>
                <p class= "animated bounceInLeft" style="animation-delay: 2s">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  <p class= "animated bounceInRight" style="animation-delay: 3s"><a href="index2.html">More Info</a></p>
              </div>
    </div>
    <div class="carousel-item">
      <img src="img/2.jpeg" class="d-block w-100" alt="...">
         <div class="carousel-caption d-none d-md-block">
                <h5 class= "animated slideInDown" style="animation-delay: 1s">Second slide label</h5>
                <p class= "animated fadeInUp" style="animation-delay: 2s">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  <p class= "animated zoomIn" style="animation-delay: 3s"><a href="index2.html">More Info</a></p>
              </div>
    </div>
    <div class="carousel-item">
      <img src="img/1.jpg" class="d-block w-100" alt="...">
         <div class="carousel-caption d-none d-md-block">
                <h5 class= "animated zoomIn" style="animation-delay: 1s">Second slide label</h5>
                <p class= "animated fadeInLeft" style="animation-delay: 2s">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                  <p class= "animated zoomIn" style="animation-delay: 1s"><a href="index2.html">More Info</a></p>
              </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


        
  <center>      
        <div class="container">
                <div class="title text-center">
                        <h1>excellent students</h1>
                        <div class="border"></div>
                    </div>
         
                
                 <section class="best_student slider ">
                  <div class="row" >
                  <div class="col-lg-2 col-sm-4 col-6">
                     <div class="slide">
                        <img src="img/1.jpeg">
                          <h5 >student7</h5>
                          <p>some information about student</p>
                     </div>
                  </div>
  
  
                  <div class="col-lg-2 col-sm-4 col-6">
                     <div class="slide">
                        <img src="img/1.jpeg">
                          <h5 >student8</h5>
                          <p>some information about student</p>
                     </div>
                  </div>
  
                 <div class="col-lg-2 col-sm-4 col-6">
                     <div class="slide">
                        <img src="img/1.jpeg">
                          <h5 >student9</h5>
                          <p>some information about student</p>
                     </div>
                  </div>
  
                  <div class="col-lg-2 col-sm-4 col-6">
                     <div class="slide">
                        <img src="img/1.jpeg">
                          <h5 >student10</h5>
                          <p>some information about student</p>
                     </div>
                  </div>
  
  
                  <div class="col-lg-2 col-sm-4 col-6">
                     <div class="slide">
                        <img src="img/1.jpeg">
                          <h5 >student11</h5>
                          <p>some information about student</p>
                     </div>
                  </div>
  
  
                  <div class="col-lg-2 col-sm-4 col-6">
                     <div class="slide">
                        <img src="img/1.jpeg">
                          <h5 >student12</h5>
                          <p>some information about student</p>
                     </div>
                  </div>
  
                      
              </div>
                 </section>
        </div>
    </center>
    <div class="pricing-area">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="single-price">
          <div class="deal-top">
            <h3>children</h3>
            <h5> less than 9  </h5> 
          </div>
          <div class="deal-bottom">
            <ul class="deal-item">
              <li>one</li>
              <li>two</li>
              <li>three</li>
              <li>four </li>
              <li>five</li>
            </ul>
            <div class="btn-area">
              <a href="#">start</a>				
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="single-price">
          <div class="deal-top">
            <h3>School</h3>
            <h5> Above 9 and less than 16</h5>
          </div>
          <div class="deal-bottom">
            <ul class="deal-item">
             <li>one</li>
              <li>two</li>
              <li>three</li>
              <li>four </li>
              <li>five</li>
            </ul>
            <div class="btn-area">
              <a href="#">Start</a>				
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="single-price">
          <div class="deal-top">
            <h3>Academy</h3>
            <h5> Up from 16 </h5> 
          </div>
          <div class="deal-bottom">
            <ul class="deal-item">
            <li>one</li>
              <li>two</li>
              <li>three</li>
              <li>four </li>
              <li>five</li>
            </ul>
            <div class="btn-area">
              <a href="#">Start</a>				
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>       


</div>

        <footer class="site-footer">

      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by 
         <a href="#">Ability lab</a>.
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>   
            </ul>
          </div>
        </div>
      </div>
</footer>
   


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>
    <script>
    window.addEventListener("scroll",function(){
    let backnavbar =document.getElementById('navbar-area');
        
        if(window.pageYOffset > 0){
            backnavbar.classList.add("cus-nav");
        }else{
            backnavbar.classList.remove("cus-nav")
        }
    });
    </script>


    <script src="js/main.js"></script>
    <script type="text/javascript">
      $('.testimonial-pics img').click(function(){
        $(".testimonial-pics img").removeClass("active");
        $(this).addClass("active");

        $(".testimonial").removeClass("active");
        $("#"+$(this).attr("alt")).addClass("active");
      });
    </script>
</body>
</html>