<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <title>Ability lab</title>

    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <link href="https://fonts.googleapis.com/css?family=Cairo:400,700" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.css">
   
</head>

<body>

    <nav class="navbar fixed-top navbar-expand-lg navbar-light fixed-top " id="navbar-area" >
        <div class="container">
               <img src="img/logo.png" width="79px" style="height: 50px;margin: 9px;background-color: #fff;" class="rounded-circle">
        <a class="navbar-brand" href="#"> Ablity Lab</a>
         
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
             <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="exam.phtml">Exam</a>
            </li>
               <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
               <li class="nav-item">
              <a class="nav-link" href="about.phtml">About Us</a>
            </li>
               <li class="nav-item">
              <a class="nav-link" href="contact.phtml">Contact Us</a>
            </li>
              <li class="nav-item">
              <a class="nav-link" href="faq.phtml">FAQs</a>
            </li>
<!--
   
--></ul>
            </div>
        </div>
      </nav>
    <div class="container-fluid no-padding">
  
  <div class="about-row">
    <div class="row">
      <div class="col-md-12 inner-about-row">
        <h1>FAQs</h1>
        <h3>How do we help? Please let us know your problem</h3>
      </div>
    </div>
  
  </div>
 

  <div id="faqs">
    <div id="faqs-accordion">
      <div class="row">
        <div class="col-md-12">
           <ul class="vertical default_list">
             <li>
                <h4>Is it possible to export my data from E-lithe, to back it up?</h4>
                <div class="answers">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum eius deleniti quia harum tempora expedita</p>
                </div>
                <h4>Is there a way to use E-lithe offline?</h4>
                <div class="answers">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum eius deleniti quia harum tempora expedita</p>
                </div>
                <h4>How do I delete a board in E-lithe?</h4>
                <div class="answers">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum eius deleniti quia harum tempora expedita</p>
                </div>
                <h4>How do I change or update the email address used in Trello?</h4>
                <div class="answers">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum eius deleniti quia harum tempora expedita</p>
                </div>        
                <h4>Set up Trello notifications to email you when task or event is due</h4>
                <div class="answers">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum eius deleniti quia harum tempora expedita</p>
                </div>
                <h4>How can I change my E-lithe avatar?</h4>
                <div class="answers">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum eius deleniti quia harum tempora expedita</p>
                </div>        
                <h4>Once a due date passes and the task is done, how do I keep the task and lose the red due date alert?</h4>
                <div class="answers">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum eius deleniti quia harum tempora expedita</p>
                </div>
              </div>
          </div>
        </div>
          </div>
    
    <a href="#" id="faqs-all">Close all</a>
  </div>
      
</div>

    
    
           <footer class="site-footer">
     
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by 
         <a href="#">Ability lab</a>.
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>   
            </ul>
          </div>
        </div>
      </div>
</footer>
    
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>
    <script src="js/main.js"></script>
       <script>
    window.addEventListener("scroll",function(){
    let backnavbar =document.getElementById('navbar-area');
        
        if(window.pageYOffset > 0){
            backnavbar.classList.add("cus-nav");
        }else{
            backnavbar.classList.remove("cus-nav")
        }
    });
    </script>
    </body>
</html>