<?php
include "header.phtml";
?>
<body>

<!-- ********************************** START ERROR MESSAGE ******************************** -->
<!-- Button HTML (to Trigger Modal) -->
<a href="#myModal" class="trigger-btn" data-toggle="modal"  id="trigger-btn" style="display: none;">Click to Open Error Modal</a>
<!-- Modal HTML -->
<div id="myModal" class="modal fade ">
    <div class="modal-dialog modal-confirm">
        <div class="modal-content">
            <div class="modal-header">
                <div class="icon-box">
                    <i class="material-icons">&#xE5CD;</i>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body text-center">
                <h4>Ooops!</h4>
                <p id="errorContent"></p>
                <button class="btn btn-success" data-dismiss="modal">Exit</button>
            </div>
        </div>
    </div>
</div>
<!-- ********************************** END ERROR MESSAGE ******************************** -->

<?php include "search.phtml";?>




<!-- end slider-------------------------------------------------------------->
<style>
    .mainCat{
        background: #2f9598;
        color: #fff;
        text-align: center;
        margin-top:2%;
        height: 50px;
        padding-top: 13px;
    }
    .examContent{
        border: 1px solid #35B1B4;
        background: #fff;
        margin: 1%;


    }

.examContent .titleExam,
.examContent p,
.examContent button{
    text-align: center;
    margin: 0 auto;
}
.examContent p{
color: #919aa3;
font-size: 14px;
font-weight: lighter;
}

.examContent .titleExam{
color: #fff;
font-size: 18px;
background: #35B1B4;
padding: 10px;
border-radius: 0 0 10px 10px;
}
.examContent a{
    width: 50%;
    margin: 5%;
    color: #fff;
}
.examsPlace{
    margin-top: 5%;
}
</style>
<div class="container">
    <?php   if ($this->view_data['form_id'] == 3){  ?>
        <div class="title text-center">
            <h1>Our top student</h1>
            <div class="border"></div>
        </div>


        <section class="best_student slider ">
            <div class="row" >
                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student7</h5>
                        <p>some information about student</p>
                    </div>
                </div>


                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student8</h5>
                        <p>some information about student</p>
                    </div>
                </div>

                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student9</h5>
                        <p>some information about student</p>
                    </div>
                </div>

                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student10</h5>
                        <p>some information about student</p>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student11</h5>
                        <p>some information about student</p>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student12</h5>
                        <p>some information about student</p>
                    </div>
                </div>
            </div>
        </section>
    <?php   }?>
</div>
<div class="container">
    <div class="title text-center">
        <h1>Our Class</h1>

        <div class="border"></div>
    </div>
    <div class="row d-flex justify-content-between">

        <?php
        if ($this->view_data['form_id'] == 1){
            foreach($this->view_data['cat'] as $row1 ){
                $cat_id = $row1['cat_id'];
                ?>
                <div class="col-sm-3">
                <div class="mainCat col-sm-12">
                  <?php  echo $row1['cat_name'];
                  echo "</div>
                        <select id='subcat' name='subCat' class='form-control'>
                        <option></option>";
                  foreach($this->view_data['sub_cat'] as $row2 ){
                      foreach ($row2 as $r){
                          if($row1['cat_id']==$r['cat_main_cat'])
                          echo '<option value="'.$r['cat_id'].'%'.$r['cat_name'].'">'.$r['cat_name'].'</option>';
                      }
                  }
                  echo "</select></div>";
                    ?>
              <!--  <div class=" col-md-4 col-sm-6">
                    <div class="card">
                        <img src="img/1.jpg" >
                        <div class="card-text">
                            <?php
/*                            echo '<a role="button" href="/Category/show_sub_cat/'.$row['cat_id'].'" disabled=""><h3>'.$row['cat_name'].'<h3></h3></a>';

                            */?>
                        </div>
                    </div>
                </div>-->

            <?php }}?>
        <?php
        if ($this->view_data['form_id'] == 2){
            foreach($this->view_data['cat'] as $row ) {
                $cat_id = $row['cat_id'];
            }
                ?>
                <div class=" col-md-4 col-sm-6">
                    <div class="card">
                        <img src="img/1.jpg" >
                        <div class="card-text">
                            <?php
                            echo '<a role="button" href="/exam/show_exams/'.$row['cat_id'].'" disabled=""><h3>'.$row['cat_name'].'<h3></h3></a>';
                            ?>
                        </div>
                    </div>
                </div>
            <?php }?>
        <?php
        if ($this->view_data['form_id'] == 3){
            foreach($this->view_data['exams'] as $row ){
                ?>
                <div class=" col-md-4 col-sm-6">
                    <div class="card">
                        <img src="img/1.jpg" >
                        <div class="card-text">
                            <?php
                            echo '<a role="button" href="/exam/takeExam/'.$row['exam_id'].'" disabled=""><h3>'.$row['exam_name'].'<h3></h3></a>';
                            ?>
                        </div>
                        <div class="">
                            <?php
                            echo '<a role="button" href="/exam/top_members_one_exam/'.$row['exam_id'].'" disabled=""><h3>Top Members<h3></h3></a>';
                            ?>
                        </div>
                    </div>
                </div>
            <?php }
        }?>



    </div>
</div>
<div class="examsPlace">
    <div class="container">
        <div class="row d-flex justify-content-between" id="loadingDiv">
    <?php
        if(!empty($this->view_data['exams'])){
            echo "<div class='col-sm-12 text-center examsTitle'><h1>".$this->view_data['selectedCat']."</h1></div>";
            foreach ($this->view_data['exams'] as $exam){
                echo '<div class="col-sm-3 examContent">
                <div class="titleExam">'.$exam['exam_name'].'</div>
                <p>'.$exam['exam_description'].'</p>
                <p>'.$exam['studentSample'] .'/'. $exam['allSample'] .'</p>
                <p>';
                switch ($exam['exam_level']){
                    case 1: echo'<span style="float: left">level : Hard</span>';break;
                    case 2: echo'<span style="float: left">level : Mediam</span>';break;
                    case 3: echo'<span style="float: left">level : Easy</span>';break;
                }
                switch ($exam['exam_price']){
                    case 0: echo'<span style="float: right">price : Free</span>';break;
                    default:echo'<span style="float: right">price : '.$exam['exam_price'].' $</span>';break;
                }
                if($exam['studentSample']==0){
                echo'</p><a type="button"  class="btn btn-info" disabled>Exam Done</a>
            </div>
            ';
                }
                else{
                    echo'</p><a type="button" href="/exam/takeExam/'.$exam['exam_id'].'" class="btn btn-info" >Get Start</a>
            </div>
            ';
                }
            }
        }
 ?>
        </div>
    </div>
</div>

        <script>
            var jq = $.noConflict();
            var errorMessage="<?php echo Message::check("unauth")?>";
            if(errorMessage!=''){
                jq("#errorContent").html(errorMessage);
                document.getElementById("trigger-btn").click();
            }

            function load_Exams(){
                var selectd=jq("select#subcat").children("option:selected").val();
                var loading="<button class='btn btn-primary' disabled><span class='spinner-border spinner-border-sm'></span>Loading..</button>";
                jq.ajax({
                    url:"/home/showCategoryExams",
                    method:"POST",
                    data:{
                        subcat:selectd
                    },
                    beforeSend:function() {
                        jq('#loadingDiv').html(loading);
                    }
                    ,
                    success:function(data)
                    {
                        html='';
                        var exams=JSON.parse(data);
                        // alert(d)
                        var count=1;
                        console.log(data);
                        jq.each( exams.data, function( index, row ) {
                            html+='<div class="col-sm-3 examContent">'
                                   +'<div class="titleExam">'
                                   +row.exam_name
                                   +'</div>'
                                   +'<p>' + row.exam_description + '</p>'
                                    +'<p>' + row.studentSample + '/' + row.allSample +'</p>'+
                            '<p>';
                            switch (row.exam_level){
                                case "1": html+='<span style="float: left">level : Hard</span>';break;
                                case "2": html+='<span style="float: left">level : Mediam</span>';break;
                                case "3": html+='<span style="float: left">level : Easy</span>';break;
                                default: html+='';
                            }
                            switch (row.exam_price){
                                case "0": html+='<span style="float: right">price : Free</span>';break;
                                default:html+='<span style="float: right">price : '+row.exam_price+' $</span>';break;
                            }
                            if(row.studentSample=="0"){
                                html+='</p><a type="button"  class="btn btn-info" disabled>Exam Done</a></div>';
                            }
                            else{
                                html+='</p><a type="button" href="/exam/takeExam/'+row.exam_id+'" class="btn btn-info" >Get Start</a></div>';
                            }

                            count++;
                        });
                        jq('#loadingDiv').html(html);
                    }
                });
            };

            jq("select#subcat").change(function () {
                load_Exams();
            })

        </script>
<?php
include "footer.phtml";
?>

