<?php
include "header.phtml";
?>
<body>

<!-- ********************************** START ERROR MESSAGE ******************************** -->
<!-- Button HTML (to Trigger Modal) -->
<a href="#myModal" class="trigger-btn" data-toggle="modal"  id="trigger-btn" style="display: none;">Click to Open Error Modal</a>
<!-- Modal HTML -->
<div id="myModal" class="modal fade ">
    <div class="modal-dialog modal-confirm">
        <div class="modal-content">
            <div class="modal-header">
                <div class="icon-box">
                    <i class="material-icons">&#xE5CD;</i>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body text-center">
                <h4>Ooops!</h4>
                <p id="errorContent"></p>
                <button class="btn btn-success" data-dismiss="modal">Exit</button>
            </div>
        </div>
    </div>
</div>
<!-- ********************************** END ERROR MESSAGE ******************************** -->

<?php include "search.phtml";?>




<!-- end slider-------------------------------------------------------------->

<section class="about" id="about">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-12">
                <div class="title text-center">
                    <h1 class= "animated slideInDown" style="animation-delay: 1s">Online Exam</h1>
                    <div class="border"></div>
                </div>
                <div class="title text-center" >
                    <p>
                        This is the last online examination system you will ever need! With our easy online exam builder you will set up your own engaging exams that fit any kind of difficulty level. Build and create your online exams & tests with great ease and provide your users with appropriate feedback, so they will have a rich learning experience.
                    </p>
                </div>

            </div>
        </div>
    </div>
</section>
<section class="about" id="about" style="background-color: #fff;">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-12">
                <div class="title text-center">
                    <h1 class= "animated slideInDown" style="animation-delay: 1s">Why use our online examination tool?</h1>
                    <div class="border"></div>
                </div>
                <div class="title text-center" >
                    <p>Do you need some serious testing software for your students? Or do you need to hand out a lot of certificates? Do you want to easily set up your exam software and invite your participants, or do you need to connect your testing software with your internal software? Start using the Online Exam Builder and this is all within reach. Take a look at all the features and solutions.</p>
                </div>

            </div>
        </div>
    </div>
</section>








<section class="services" id="services">
    <div class="container ">

        <div class="row">
            <div class=" col-md-4 col-sm-6 s_item text-center why2">
                <div class="s_icon">
                    <i class="fa fa-twitter animated bounceInRight" style="animation-delay: 1s"></i>

                </div>
                <h5  class= "animated bounceInLeft" style="animation-delay: 2s">Easy to use</h5>
                <p class= "animated zoomIn" style="animation-delay: 1s">Our exam builder is simple and easy to use. For students as well as for the administrators. With our online exam builder it's easy to start, which makes it more fun.</p>
            </div>
            <div class=" col-md-4 col-sm-6 s_item text-center why2">
                <div class="s_icon">
                    <i class="fa fa-twitter animated bounceInRight" style="animation-delay: 1s"></i>
                </div>
                <h5 class= "animated bounceInLeft" style="animation-delay: 2s">Looks great on all devices</h5>
                <p class= "animated zoomIn" style="animation-delay: 1s">It doesn't matter if you are on a phone, tablet or pc: your online exam will look beautiful. Our online examination system is fully responsive, so you can engage your audience on any platform.</p>
            </div>
            <div class=" col-md-4 col-sm-6 s_item text-center why2">
                <div class="s_icon">
                    <i class="fa fa-twitter animated bounceInRight" style="animation-delay: 1s"></i>
                </div>
                <h5 class= "animated bounceInLeft" style="animation-delay: 2s">Awesome support</h5>
                <p class= "animated zoomIn" style="animation-delay: 1s">Do you have any questions about our online examination software? Our support owls are always by your side and provide you with the best possible support!</p>
            </div>
        </div>
    </div>
</section>


    <div class="container" align="center">
        <div class="title text-center">
            <h1>excellent students</h1>
            <div class="border"></div>
        </div>


        <section class="best_student slider ">
            <div class="row" >
                <?php
                $i=1;
                foreach($this->view_data['top'] as $row ){
                ?>
                <div class="col-lg-2 col-sm-4 col-6">
                    <div class="slide">
                        <p ><?php echo $i++;?></p>
                      <a class="Studentinfo" data-user-id="<?php echo $row['user_id'] ?>" data-toggle="modal" data-target=".bd-example-modal-lgg"><img src="/pictures/<?php echo $row['image']; ?>"> </a>
                        <h5 ><?php echo $row['user_name']?></h5>
                    </div>
                </div>
                <?php } ?>
            </div>
        </section>
    </div>

<div class="testimonial-section">
    <div class="inner-width">
        <h1>What Our Clients Say</h1>
        <div class="testimonial-pics">
            <img src="/pictures/p1.png" alt="test-1" class="active">
            <img src="/pictures/p2.png" alt="test-2">
            <img src="/pictures/p3.png" alt="test-3">
            <img src="/pictures/p4.png" alt="test-4">
        </div>

        <div class="testimonial-contents">
            <div class="testimonial active" id="test-1">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab consequatur et adipisci ut, impedit cumque, similique, eum tenetur, numquam eligendi aliquid. Nulla sit, cupiditate corporis labore, modi natus officiis asperiores!</p>
                <span class="description">Emy / Developer</span>
            </div>

            <div class="testimonial" id="test-2">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elimet, consectetur adipisicing eli t. Ab consequatur et adipisci ut, impedit cumque, similique, eum tenetur, numquam eligendi aliquid. Nulla sit, cupiditate corporis labore, modi natus officiis asperiores!</p>
                <span class="description">Carla / Developer</span>
            </div>

            <div class="testimonial" id="test-3">
                <p>Lorem  similique, eum tenetur, numquam eligendi aliquid. Nulla sit, cupiditate corporis labore, modi natus officiis asperiores!</p>
                <span class="description">Thomas / Developer</span>
            </div>

            <div class="testimonial" id="test-4">
                <p>Lorem ipsum dolorng elit. Ab consequatur et adipisci ut, impedit cumque, similique, eum tenetur, numquam eligendi aliquid. Nulla sit, cupiditate corporis labore, modi natus officiis asperiores!</p>
                <span class="description">Monica / Developer</span>
            </div>
        </div>
    </div>
</div>


<!--model for top talents-->
<div class="modal fade bd-example-modal-lgg" id="modelContent" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content" id="talentExam2" style="width: 50%;">
        </div>
    </div>
</div>


<!-- oooooo -->
<style>
    .mainCat{
        background: #2f9598;
        color: #fff;
        text-align: center;
        margin-top:2%;
        height: 50px;
        padding-top: 13px;
    }
    .examContent{
        border: 1px solid #35B1B4;
        background: #fff;
        margin: 1%;


    }

.examContent .titleExam,
.examContent p,
.examContent button{
    text-align: center;
    margin: 0 auto;
}
.examContent p{
color: #919aa3;
font-size: 14px;
font-weight: lighter;
}

.examContent .titleExam{
color: #fff;
font-size: 18px;
background: #35B1B4;
padding: 10px;
border-radius: 0 0 10px 10px;
}
.examContent a{
    width: 50%;
    margin: 5%;
    color: #fff;
}
.examsPlace{
    margin-top: 5%;
}
</style>
<div class="container">
    <?php   if ($this->view_data['form_id'] == 3){  ?>
        <div class="title text-center">
            <h1>Our top student</h1>
            <div class="border"></div>
        </div>


        <section class="best_student slider ">
            <div class="row" >
                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student7</h5>
                        <p>some information about student</p>
                    </div>
                </div>


                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student8</h5>
                        <p>some information about student</p>
                    </div>
                </div>

                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student9</h5>
                        <p>some information about student</p>
                    </div>
                </div>

                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student10</h5>
                        <p>some information about student</p>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student11</h5>
                        <p>some information about student</p>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student12</h5>
                        <p>some information about student</p>
                    </div>
                </div>
            </div>
        </section>
    <?php   }?>
</div>
<div class="container">
    <div class="title text-center">
        <h1>Our Class</h1>

        <div class="border"></div>
    </div>
    <div class="row d-flex justify-content-between">

        <?php
        if ($this->view_data['form_id'] == 1){
            foreach($this->view_data['cat'] as $row1 ){
                $cat_id = $row1['cat_id'];
                ?>
                <div class="col-sm-3">
                <div class="mainCat col-sm-12">
                  <?php  echo $row1['cat_name'];
                  echo "</div>
                        <select id='subcat' name='subCat' class='form-control'>
                        <option></option>";
                  foreach($this->view_data['sub_cat'] as $row2 ){
                      foreach ($row2 as $r){
                          if($row1['cat_id']==$r['cat_main_cat'])
                          echo '<option value="'.$r['cat_id'].'%'.$r['cat_name'].'">'.$r['cat_name'].'</option>';
                      }
                  }
                  echo "</select></div>";
                    ?>
              <!--  <div class=" col-md-4 col-sm-6">
                    <div class="card">
                        <img src="img/1.jpg" >
                        <div class="card-text">
                            <?php
/*                            echo '<a role="button" href="/Category/show_sub_cat/'.$row['cat_id'].'" disabled=""><h3>'.$row['cat_name'].'<h3></h3></a>';

                            */?>
                        </div>
                    </div>
                </div>-->

            <?php }}?>
        <?php
        if ($this->view_data['form_id'] == 2){
            foreach($this->view_data['cat'] as $row ) {
                $cat_id = $row['cat_id'];
            }
                ?>
                <div class=" col-md-4 col-sm-6">
                    <div class="card">
                        <img src="img/1.jpg" >
                        <div class="card-text">
                            <?php
                            echo '<a role="button" href="/exam/show_exams/'.$row['cat_id'].'" disabled=""><h3>'.$row['cat_name'].'<h3></h3></a>';
                            ?>
                        </div>
                    </div>
                </div>
            <?php }?>
        <?php
        if ($this->view_data['form_id'] == 3){
            foreach($this->view_data['exams'] as $row ){
                ?>
                <div class=" col-md-4 col-sm-6">
                    <div class="card">
                        <img src="img/1.jpg" >
                        <div class="card-text">
                            <?php
                            echo '<a role="button" href="/exam/takeExam/'.$row['exam_id'].'" disabled=""><h3>'.$row['exam_name'].'<h3></h3></a>';
                            ?>
                        </div>
                        <div class="">
                            <?php
                            echo '<a role="button" href="/exam/top_members_one_exam/'.$row['exam_id'].'" disabled=""><h3>Top Members<h3></h3></a>';
                            ?>
                        </div>
                    </div>
                </div>
            <?php }
        }?>



    </div>
</div>
<div class="examsPlace">
    <div class="container">
        <div class="row d-flex justify-content-between" id="loadingDiv">
    <?php
        if(!empty($this->view_data['exams'])){
            echo "<div class='col-sm-12 text-center examsTitle'><h1>".$this->view_data['selectedCat']."</h1></div>";
            foreach ($this->view_data['exams'] as $exam){
                echo '<div class="col-sm-3 examContent">
                <div class="titleExam">'.$exam['exam_name'].'</div>
                <p>'.$exam['exam_description'].'</p>
                <p>'.$exam['studentSample'] .'/'. $exam['allSample'] .'</p>
                <p>';
                switch ($exam['exam_level']){
                    case 1: echo'<span style="float: left">level : Hard</span>';break;
                    case 2: echo'<span style="float: left">level : Mediam</span>';break;
                    case 3: echo'<span style="float: left">level : Easy</span>';break;
                }
                switch ($exam['exam_price']){
                    case 0: echo'<span style="float: right">price : Free</span>';break;
                    default:echo'<span style="float: right">price : '.$exam['exam_price'].' $</span>';break;
                }
                if($exam['studentSample']==0){
                echo'</p><a type="button"  class="btn btn-info" disabled>Exam Done</a>
            </div>
            ';
                }
                else{
                    echo'</p><a type="button" href="/exam/takeExam/'.$exam['exam_id'].'" class="btn btn-info" >Get Start</a>
            </div>
            ';
                }
            }
        }
 ?>
        </div>
    </div>
</div>

        <script>
            var errorMessage="<?php echo Message::check("unauth")?>";
            if(errorMessage!=''){
                $("#errorContent").html(errorMessage);
                document.getElementById("trigger-btn").click();
            }

            function load_Exams(){


                var selectd=$("select#subcat").children("option:selected").val();
                var loading="<button class='btn btn-primary' disabled><span class='spinner-border spinner-border-sm'></span>Loading..</button>";
                $.ajax({
                    url:"/home/showCategoryExams",
                    method:"POST",
                    data:{
                        subcat:selectd
                    },
                    beforeSend:function() {
                        $('#loadingDiv').html(loading);
                    }
                    ,
                    success:function(data)
                    {
                        console.log(data);

                        html='<h5 style="display: block; width: 100%; text-align: center ;background: #fff; padding: 20px; color:#37b2b5; font-size: 24px; font-weight: bolder; text-transform: uppercase; ">'+$("select#subcat").children("option:selected").text()+'</h5>';
                        var exams=JSON.parse(data);

                       if(exams.data=="no result"){
                           html='<h5 style="display: block; width: 100%; text-align: center ;background: #fff; padding: 20px; color:#37b2b5; font-size: 24px; font-weight: bolder; text-transform: uppercase; ">'+exams.data+'</h5>';
                       }
                       else{

                           $.each( exams.data, function( index, row ) {
                               html+='<div class="col-sm-3 examContent">'
                                   +'<div class="titleExam">'
                                   +row.exam_name
                                   +'</div>'
                                   +'<p>' + row.exam_description + '</p>'

                                   +'<p>Chances :' + row.studentSample + '/' + row.allSample +'</p>'+
                                   '<p>Examiner: ' + row.examiner + '</p>'
                               '<p>';
                               switch (row.exam_level){
                                   case "1": html+='<span style="float: left">level : Hard</span>';break;
                                   case "2": html+='<span style="float: left">level : Mediam</span>';break;
                                   case "3": html+='<span style="float: left">level : Easy</span>';break;
                                   default: html+='';
                               }
                               switch (row.exam_price){
                                   case "0": html+='<span style="float: right">price : Free</span>';break;
                                   default:html+='<span style="float: right">price : '+row.exam_price+' $</span>';break;
                               }
                               if(row.studentSample=="0"){
                                   html+='</p><a type="button"  class="btn btn-info" disabled>Exam Done</a></div>';
                               }
                               else{
                                   html+='</p><a type="button" href="/exam/takeExam/'+row.exam_id+'" class="btn btn-info" >Get Start</a></div>';
                               }

                           });
                       }

                        $('#loadingDiv').html(html);

                    }
                });
            };




            $("select#subcat").change(function () {
                load_Exams();
            })

            $('.Studentinfo').on('click', function () {
                var data = 'user_id=' + encodeURIComponent($(this).attr('data-user-id'));
                var url = '/exam/student_profile';
                var _this = $(this);
                $.ajax({
                    url: url,//   var url=$('#news').attr('action');
                    method: 'POST',
                    dataType: 'json',// data type that i want to return
                    data: data,// var form=$('#news').serialize();
                    success: function (data) {
                        console.log(data);
                        html='';
                        var i=1;
                        $.each( data, function( index, row ) {


                            html+='<div class="our-team">\n' +
                                '                    <div class="pic">\n' +
                                '                        <img src="/pictures/'+row.image+'">\n' +
                                '                    </div>\n' +
                                '                    <div class="team-content">\n' +
                                '                        <h3 class="title">'+row.full_name+'</h3>\n' +
                                '                        <span class="post">Email:  '+row.user_email+'</span>\n' +
                                '                        <span class="post">Phone:  '+row.phone+'</span>\n' +
                                '                    </div>\n' +
                                '                    <ul class="social">\n' +
                                '                        <li>\n' +
                                '                            <a href="#"  target="_blank"class="fa fa-facebook"></a>\n' +
                                '                        </li>\n' +
                                '                        <li>\n' +
                                '                            <a href="#" class="fa fa-twitter"></a>\n' +
                                '                        </li>\n' +
                                '                        <li>\n' +
                                '                            <a href="#" class="fa fa-google-plus"></a>\n' +
                                '                        </li>\n' +
                                '                        <li>\n' +
                                '                            <a href="#" class="fa fa-linkedin"></a>\n' +
                                '                        </li>\n' +
                                '                    </ul>\n' +
                                '                </div>';
                            i++;
                        });

                        $('#talentExam2').html(html);
                        $('#modelContent').modal('show');
                    },
                    error: function (xhr, status, error) {
                        alert(xhr.responseText);
                    }
                });
                return (false);
            });

        </script>

        <?php
include "footer.phtml";
?>
