<?php
include "header.phtml";
?>
    <body>


<div class="slider">



    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel" >
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" >
            <div class="carousel-item active" >
                <img src="/static/img/1.jpeg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>First slide label</h5>
                    <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                    <a href="#work">Check Our Work</a>
                </div>
            </div>
            <div class="carousel-item">
                <img src="/static/img/1.jpeg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Second slide label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="/static/img/1.jpeg "class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Third slide label</h5>
                    <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

</div>




<!-- end slider-------------------------------------------------------------->

<div class="container">
    <?php   if ($this->view_data['form_id'] == 3){  ?>
        <div class="title text-center">
            <h1>Our top student</h1>
            <div class="border"></div>
        </div>


        <section class="best_student slider ">
            <div class="row" >
                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student7</h5>
                        <p>some information about student</p>
                    </div>
                </div>


                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student8</h5>
                        <p>some information about student</p>
                    </div>
                </div>

                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student9</h5>
                        <p>some information about student</p>
                    </div>
                </div>

                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student10</h5>
                        <p>some information about student</p>
                    </div>
                </div>


                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student11</h5>
                        <p>some information about student</p>
                    </div>
                </div>


                <div class="col-lg-2 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/static/img/1.jpeg">
                        <h5 >student12</h5>
                        <p>some information about student</p>
                    </div>
                </div>


            </div>
        </section>
    <?php   }?>
</div>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <p>&copy; 2020 By
                    <a href="#"> ability lab</a>
                </p>
            </div>
            <div class="col-xs-12 col-sm-6 text-right">
                <a href="#">
                    <i class="fa fa-facebook"></i>
                </a>
                <a href="#">
                    <i class="fa fa-instagram"></i>
                </a>
                <a href="#">
                    <i class="fa fa-twitter"></i>
                </a>
                <a href="#">
                    <i class="fa fa-youtube"></i>
                </a>
            </div>
        </div>
    </div>
</footer>



















<div class="container">
    <div class="title text-center">
        <h1>Our Class</h1>

        <div class="border"></div>
    </div>
    <div class="row">
        <?php
        if ($this->view_data['form_id'] == 1){
            foreach($this->view_data['cat'] as $row ){
                $cat_id = $row['cat_id'];

                ?>
                <div class=" col-md-4 col-sm-6">
                    <div class="card">
                        <img src="img/1.jpg" >
                        <div class="card-text">
                            <?php
                            echo '<a role="button" href="/Category/show_sub_cat/'.$row['cat_id'].'" disabled=""><h3>'.$row['cat_name'].'<h3></h3></a>';

                            ?>



                        </div>
                    </div>
                </div>

            <?php }}?>

        <?php
        if ($this->view_data['form_id'] == 2){
            foreach($this->view_data['cat'] as $row ){
                $cat_id = $row['cat_id'];

                ?>
                <div class=" col-md-4 col-sm-6">
                    <div class="card">
                        <img src="img/1.jpg" >
                        <div class="card-text">
                            <?php
                            echo '<a role="button" href="/exam/show_exams/'.$row['cat_id'].'" disabled=""><h3>'.$row['cat_name'].'<h3></h3></a>';

                            ?>



                        </div>
                    </div>
                </div>

            <?php }}?>

        <?php
        if ($this->view_data['form_id'] == 3){
            foreach($this->view_data['exams'] as $row ){


                ?>
                <div class=" col-md-4 col-sm-6">
                    <div class="card">
                        <img src="img/1.jpg" >
                        <div class="card-text">
                            <?php
                            echo '<a role="button" href="/exam/takeExam/'.$row['exam_id'].'" disabled=""><h3>'.$row['exam_name'].'<h3></h3></a>';

                            ?>
                        </div>

                        <div class="">
                            <?php
                            echo '<a role="button" href="/exam/top_members_one_exam/'.$row['exam_id'].'" disabled=""><h3>Top Members<h3></h3></a>';

                            ?>
                        </div>
                    </div>
                </div>

            <?php }}?>



    </div>
</div>

<div class="con">
    <section class="about contact" id="contact">
        <div class="container">
            <div class="title text-center">
                <h1>Our Contact</h1>
                <div class="border"></div>
            </div>
            <div class="row ">
                <div class="col-xs-12 col-sm-10 col-sm-offset-1">
                    <div class="inner_about">
                        <form action="">
                            <input type="text" name="" id="" placeholder="Full Name" class="form-control">
                            <input type="email" name="" id="" placeholder="Email Address" class="form-control">
                            <input type="text" name="" id="" placeholder="Subject" class="form-control">
                            <textarea name="" id="" class="form-control" placeholder="Message Body"></textarea>
                            <input type="submit" value="Send" class="btn btn-info">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <p>&copy; 2020 By
                    <a href="#">Ability lab  </a>
                </p>
            </div>
            <div class="col-xs-12 col-sm-6 text-right">
                <a href="#">
                    <i class="fa fa-facebook"></i>
                </a>
                <a href="#">
                    <i class="fa fa-instagram"></i>
                </a>
                <a href="#">
                    <i class="fa fa-twitter"></i>
                </a>
                <a href="#">
                    <i class="fa fa-youtube"></i>
                </a>
            </div>
        </div>
    </div>
</footer>





<?php

include "footer.phtml";

