
<div class="container-fluid searchArea">
<div align="center" >
    <input type="text" name="search" id="search" placeholder="Search Exam" class="form-control" />
</div>
<ul class="list-group"  id="result"></ul>
</div>

<script>

    $(document).ready(function () {
    function search_Exams(){
        var searchTxt=$("#search").val();
        console.log(searchTxt);
        // var selectd=jq("select#subcat").children("option:selected").val();
        // var loading="<button class='btn btn-primary' disabled><span class='spinner-border spinner-border-sm'></span>Loading..</button>";
        $.ajax({
            url:"/home/search",
            method:"POST",
            data:{
                search:searchTxt
            },
            /*beforeSend:function() {
                jq('#loadingDiv').html(loading);
            }
            ,*/
                success:function(data)
                {

                    html='';
                    $('#result').html(html);
                    var exams=JSON.parse(data);
                    html='';
                    $.each( exams.data, function( index, row ) {
                        html+="<li class=\"list-group-item link-class\" value='"+row.exam_id+"'>"+row.exam_name+"</li>";
                    });
                    $('#result').html(html);
                }
            });
    };

        $("#search").keyup(function () {
        search_Exams();
    });
    /*
    jq("#search").blur(function () {
        jq('#result').html("");
    });
*/
        $('#result').on('click', 'li', function() {
        var click_text = $(this).text().split('|');
            $('#search').val($.trim(click_text[0]));
            $("#result").html('');
        result_Exams($(this).attr("value"));
    });
/******************************************************************************/
    function result_Exams(liVal){
        var searchTxt=liVal;
        $.ajax({
            url:"/home/showCategoryExams",
            method:"POST",
            data:{
                resultSelect:searchTxt
            },
            /*beforeSend:function() {
                jq('#loadingDiv').html(loading);
            }
            ,*/
            success:function(data)
            {
                html='';
                var exams=JSON.parse(data);
                console.log(data);
                $.each( exams.data, function( index, row ) {
                    html+='<div class="col-sm-3 examContent">'
                        +'<div class="titleExam">'
                        +row.exam_name
                        +'</div>'
                        +'<p>' + row.exam_description + '</p>'
                        +'<p>' + row.studentSample + '/' + row.allSample +'</p>'+
                        '<p>';
                    switch (row.exam_level){
                        case "1": html+='<span style="float: left">level : Hard</span>';break;
                        case "2": html+='<span style="float: left">level : Mediam</span>';break;
                        case "3": html+='<span style="float: left">level : Easy</span>';break;
                        default: html+='';
                    }
                    switch (row.exam_price){
                        case "0": html+='<span style="float: right">price : Free</span>';break;
                        default:html+='<span style="float: right">price : '+row.exam_price+' $</span>';break;
                    }
                    if(row.studentSample=="0"){
                        html+='</p><a type="button"  class="btn btn-info" disabled>Exam Done</a></div>';
                    }
                    else{
                        html+='</p><a type="button" href="/exam/takeExam/'+row.exam_id+'" class="btn btn-info" >Get Start</a></div>';
                    }

                });
                $('#loadingDiv').html(html);
            }
        });
    };
});

</script>
