<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>take Exam</title>
    <script typy="text/javascript">

        window.addEventListener('beforeunload', (event) => {
            //localStorage.removeItem('timimg');
            event.preventDefault();
            event.returnValue = `Are you sure you want to leave?,we will save the Exam Mark`;
            document.getElementById("endExam").click();

        });

        var duration=<?php echo $this->view_data["duration"]?>;
        var examId="<?php echo $this->view_data["exam_id"]?>";
        var timeLeft=1*duration*60;
        function timeout()
        {
            console.log();
            if (!localStorage.timimg) {
                localStorage.timimg=timeLeft;
                localStorage.examId=examId;
            }
            if(localStorage.examId!=examId){
                localStorage.timimg=timeLeft;
                localStorage.examId=examId;
            }

            var hours=Math.floor(Number(localStorage.timimg)/3600);
            var minute=Math.floor(Number((localStorage.timimg-(hours*60*60)))/60);
            var second=Number(localStorage.timimg)%60;
            console.log(localStorage.timimg);
            var hrs=checktime(hours);
            var mint=checktime(minute);
            var sec=checktime(second);
            if(Number(localStorage.timimg)<=0)
            {
                localStorage.timimg=timeLeft;
                clearTimeout(tm);
                document.getElementById("endExam").click();
            }
            else
            {
                // document.getElementById("time").innerHTML=hrs+":"+mint+":"+sec;
                document.getElementById("time").innerHTML="<div class='hour'>"+hrs+"<small>h</small></div>"+"<div class='minute'>"+":"+mint+"<small>min</small></div>"+"<div class='second'>"+":"+sec+"<small>sec</small></div>";
                localStorage.timimg--;
            }
            var tm= setTimeout(function(){timeout()},1000);
        }
        function checktime(msg)
        {
            if(msg<10)
            {
                msg="0"+msg;
            }
            return msg;
        };



    </script>
</head>
<body onload="timeout()" oncontextmenu="return false;">
<div id="time" ></div>
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form class="form" method="post" id="form1">
                <div class="txt-ctr"><h2><?php echo $this->view_data['exam_name'];?></h2></div>
<?php
    $i=0;
    foreach($this->view_data['q'] as $ques ){
        echo "<p class='Q_Content'>".$ques["q_content"]."</p>";
        if($ques["q_img"]!=null){
            echo" <img class='examStudentIMG rounded mx-auto d-block' src='/images/examsImg/".$ques["q_img"]."'>";
        }
        echo"<ul class='que'  id=\"sr1\">
                <input type='hidden' name='q_id".$i."'  value=".$ques["q_id"]."> ";
        foreach ($this->view_data['choice'] as $choice){
            $inputID=0;
            foreach ($choice as $row){
                $inputID++;
                if($row["q_id"]===$ques["q_id"]){
                    echo "<li class='q_".$i."' >
                            <div class=\"inputGroup\">
                                <input id='_".$i.$inputID."'  name=q_".$i." type=\"radio\" value=".$row["choice_id"].">
                                <label for='_".$i.$inputID."'>".$row["choice_content"]."</label>
                            </div>
                        </li> ";
                }
               //class="simple-radio" <div class='check q_".$i.$i."'><span class=\"no\">&nbsp;</span><span class=\"yes\">&#10003;</span></div>
            }
        }
/*
        echo "<li>".Message::check("trueChoice".$i)."</li>";
        echo "<li>".Message::check("falseChoice".$i)."</li>";
        echo "<li>".Message::check("q_".$i)."</li>";*/
        echo "</ul><hr>";
        $i++;
    }
?>
                <div class="col-sm-11">
                    <input type="submit" class="form-control btn btn-outline-primary btnendexam"  name="endExam" id="endExam" value="done"></input>
                </div>
                <input type="hidden" name="q_num" value=<?php echo $i ?>>
                </form>
            </div>
        <div class="col-md-12"></div>
        <div class="col-md-3"></div>
        <div class="col-md-6"><?php /*echo Message::check("trueExam");
                                    echo Message::check("examDegreeT");
                                    echo Message::check("falseExam");
                                    echo Message::check("examDegreeF");
                                */?>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
<script src="/js/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
<script>
</script>

</body>
</html>