<!DOCTYPE html>
<?php
include "header.phtml";
?>
<html>
<head>

    <title>Top Members in One Exam</title>
</head>


<div id="time" ></div>
<div class="container">


    <table class="table" style="width:100%; border-spacing: 5px;">
        <tr>
            <td><h4>User_name</h4></td>
            <td><h4>Marks</h4></td>
            <td><h4>date</h4></td>



        </tr>
        <?php
        foreach($this->view_data['top_M_exam'] as $row ){
            $user_name =$row['user_name'];
            $user_id =$row['user_id'];
            $marks =$row['degrees'];

//            $exam_name =$row['exam_name'];
            ?>
            <tr>
                <td><a href="/exam/student_profile/<?php echo $user_id ?>"><?php echo $user_name?></a></td>
                <td><?php echo $marks ?></td>
                <td><?php echo $row['user_exam_date']; ?></td>



            </tr>
        <?php }

        ?>


    </table>

</div>


</body>
</html>