
<script src="/layout/js/jquery.validate.js"></script>
<script src="/layout/js/main.js"></script>
<script src="/layout/js/script.js"></script>
<script>
    $(document).ready(function() {
        $('#signupForm').submit(function() {
            if ($('input:checkbox', this).length == $('input:checked', this).length ) {
                // everything's fine...
            } else {
                alert('Please tick all checkboxes!');
                return false;
            }
        });
    });
</script>

</body>
</html>
