<!DOCTYPE html>
    <!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
    <!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
    <!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
    <!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
          <title><?php echo(isset($this->pageTitle)?$this->pageTitle:'page n'); ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <link rel="stylesheet" href="/css/bootstrap.min1.css">
        <link rel="stylesheet" href="/css/bootstrap-responsive.min1.css">
        <link rel="stylesheet" href="/css/font-awesome.min1.css">
        <link rel="stylesheet" href="/css/main.css">
        <link rel="stylesheet" href="/css/sl-slide.css">
        <link rel="stylesheet" href="/css/bootstrap-rtl.min.css">
          <link rel="stylesheet" href="/css/bootstrap-rtl.css">

            <link rel="stylesheet" href="/css/style_news.css">
            <link rel="stylesheet" href="/css/styles.css">

        <script src="/js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Amiri|Tajawal|Vibes&display=swap" rel="stylesheet">
        <!-- Le fav and touch icons -->
        <link rel="shortcut icon" href="/images/ico/favicon.ico">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/images/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/images/ico/apple-touch-icon-57-precomposed.png">
    </head>

    <body style="background:white;">

      <!--Header-->
      <header class="navbar navbar-fixed-top">
          <div class="navbar-inner">
              <div class="container">
                  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </a>
                  <a id="logo" class="pull-left" href="index"></a>
                  <div class="nav-collapse collapse pull-right">
                      <ul class="nav">
                        <li class="login">

                          <?php

                          if(Session::logged()) echo '<a  href="/home/logout">تسجيل الخروج <i class="icon-unlock"></i></a>'; else echo'<a data-toggle="modal" href="#loginForm">تسجيل الدخول <i class="icon-lock"></i> </a>'; ?>

                        </li>

                          <li><a href="/home/aboutUs">من نحن</a></li>
                          <li><a href="/home/services">خدماتنا</a></li>
                          <li><a href="/home/Portfolio">نبذة</a></li>
                                <?php
                                foreach ($this->view_data['exam'] as $value)
                                {

                                    echo $value['exam_name'];
                                echo'  <li >'.$value["exam_name"].'</li>';

                                }
                                 ?>


                          <li><a href="/home/articles">مقالات</a></li>
                          <li><a href="/home/contact">تواصل معانا</a></li>
                            <li class="active"><a href="/home/index">الرئيسية</a></li>

                      </ul>
                  </div><!--/.nav-collapse -->
              </div>
          </div>
      </header>
      <!-- /header -->
      <?php echo Message::check('main');  ?>
