<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="icon" href="images/logo.png" type="image/png" sizes="16x16">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/fontawesome.min.css">
        <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/css/style.css">
    <!--<link rel="stylesheet" href="/css/index.css">-->
    <link rel="stylesheet" href="/static/css/styleexam.css">
    <title>ability lab</title>
</head>
<body>

<!--navbar-------------------------------------------------------------->
<nav class="navbar navbar-expand-lg ">
    <a class="navbar-brand" href="#"><img src="/static/img/logo.png"  width="70px" class="rounded-circle" style="margin-bottom: 18px;"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/home/index">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Talents</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    category
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <?php
                    $category=new Category();
                    foreach ($category->allSubCate() as $subcat){
                        echo '<a class="dropdown-item" href="#">'.$subcat["cat_name"].'</a>';
                    }
                    ?>
                </div>
            </li>
        </ul>

        <!----------------------------- start trying---------------------------------------------->

        <nav class="main-nav" style="position: relative;">
            <ul>
                <!-- inser more links here -->
                <?php if(Session::has('userID')){
                    echo '<li style="width: 80px; height: 80px; overflow: hidden; position: absolute; top: 8%; left: -50%;">
                    <img class="" src="/pictures/'.Session::get('userImg').'" style=" width:100%; height:100%; border-radius: 50% "></li>
                <li><a class="btn btn-outline-secondary my-2 my-sm-0" href="/user/logout" style="color:gray; margin-right: 10px; padding: 10px;">Log Out</a></li>';
                }else{

                    echo '<li><a class="btn btn-outline-success my-2 my-sm-0" href="#0" style=" color:green; margin-right: 10px; padding: 10px;">Sign in</a></li>';
       //         <li><a class="btn btn-outline-success my-2 my-sm-0" href="#0" style=" color:green; margin-right: 10px; padding: 10px;">Sign Out</a></li>'
                }
                ?>
            </ul>
        </nav>
        <div class="cd-user-modal"> <!-- this is the entire modal form, including the background -->
            <div class="cd-user-modal-container"> <!-- this is the container wrapper -->
                <ul class="cd-switcher">
                    <li><a href="#0">Sign in</a></li>
                    <li><a href="#0">New account</a></li>
                </ul>
                <div id="cd-login"> <!-- log in form -->
                    <form class="cd-form"  method="post" action="/user/login">

                        <div class="fieldset">
                            <div class="input-group mb-3">
                                <div class="input-group-append">
                                    <span class="input-group-text" style="background: #ffffff;"><img src="/image/email (4).png" width="20px" height="20px"></span>
                                </div>
                                <input class="form-control"  id="signin-email" type="text" name="username" placeholder="  Enter Your Email" >
                                <?php echo Message::check('username');?>
                            </div>
                        </div>
                        <div class="fieldset">
                            <!--                        <div class="input-group mb-3">-->
                            <label class="image-replace cd-password" for="signin-password">Password</label>
                            <input class=" form-control full-width has-padding has-border" id="signin-password" name="password" type="password"  placeholder="Enter Your Password">
                            <?php// echo Message::check('password');  ?>
                            <a href="#0" class="hide-password">Show</a>
                        </div>
                        <!--                    </div>-->

                        <div class="fieldset">
                            <button type="submit" class="btn btn-primary" name="login"  value="login"> login</button>

                        </div>
                    </form>



                </div>
                <!--           ---------------------end login----------------------------------------->


                <div id="cd-signup"> <!-- sign up form -->
                    <form class="cd-form" name="regform" id="signupForm" method="post" action="/user/add" enctype="multipart/form-data">


                        <div id="preview-container">
                            <div class="text-center">
                                <h4> Your Image Profile </h4>
                                <img class="preview" src="/image/email (5).png"/>
                                <!--  <input type="button" value="Upload" class="upload-image btn-default"/>-->
                                <input id="upload" type="file" name="fileToUpload" accept="image/*"/>
                                <img class="preview" src="/image/download (2).jpg"style="    width: 31px;
    height: 28px;
    margin-left: -30px;
    margin-bottom: -60px;">
                            </div>
                        </div>


                        <p class="fieldset">
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text" style="background: #ffffff;"><img src="/image/images (1).png" width="20px" height="20px"></span>
                            </div>

                            <input class="form-control" id="username" type="text" name="username" onkeyup="lettersOnly(this)" placeholder="   Enter Your UserName" >
                            <?php// echo Message::check('username');  ?>
                        </div>
                        </p>

                        <p class="fieldset">
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text" style="background: #ffffff;"><img src="/image/email (4).png" width="20px" height="20px"></span>
                            </div>
                            <input class="form-control" id="fullname" type="text" name="full_name" onkeyup="lettersOnlyTwo(this)" placeholder="   Enter Your FullName" >
                            <?php// echo Message::check('full_name');  ?>
                        </div>
                        </p>

                        <p class="fieldset">
                        <div class="input-group mb-3">
                            <div class="input-group-append" >
                                <select style="background: #ffffff; color: #007bff">
                                    <option value="+967">+967</option>
                                    <option value="+955">+955</option>
                                    <option value="+224">+224</option>
                                    <option value="+968">+968</option>
                                </select>

                            </div>
                            <input class="form-control" id="phone" type="text" name="phone" onkeyup="numbersOnly(this)" placeholder="   Enter Your Phone" >
                        </div>
                        <?php// echo Message::check('phone');  ?>
                        </p>

                        <p class="fieldset">
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text" style="background: #ffffff;"><img src="/image/download (4).png" width="20px" height="20px"></span>
                            </div>
                            <input class="form-control" id="email" type="email" name="email" placeholder="  Enter Your Email" >
                            <div class="input-group-append">
                                <?php echo Message::check('email');  ?>

                            </div>

                        </div>
                        </p>

                        <p class="fieldset">

                            <label class="image-replace cd-password" for="signin-password">Password</label>
                            <input class=" form-control full-width has-padding has-border" id="password" name="password" type="password"  placeholder="Enter Your Password">
                            <a href="#0" class="hide-password">Show</a>
                            <?php //echo Message::check('password');  ?>

                        </p>

                        <div class="form-group">
                            <label for="Select" class="col-sm-2 control-label">Type</label>

                            <select id="Select" class="form-control" name="type">
                                <option value="3">User</option>
                                <option value="2">Examiner</option>
                            </select>
                            <?php// echo Message::check('type');  ?>
                        </div>

                        <p class="fieldset">
                            <input type="checkbox" name="terms"  id="accept-terms" required >
                            <label for="accept-terms" >I agree to the <a href="termsPage.php">Terms</a></label>
                        </p>



                        <p class="fieldset">
                            <button type="submit" class="btn btn-primary" name="submit"  value="register">add user</button>
                        </p>
                    </form>

                    <!-- <a href="#0" class="cd-close-form">Close</a> -->
                </div> <!-- cd-signup -->

                <div id="cd-reset-password"> <!-- reset password form -->
                    <p class="cd-form-message">Lost your password? Please enter your email address. You will receive a link to create a new password.</p>

                    <form class="cd-form">
                        <p class="fieldset">
                            <label class="image-replace cd-email" for="reset-email">E-mail</label>
                            <input class="full-width has-padding has-border" id="reset-email" type="email" placeholder="E-mail">
                            <span class="cd-error-message">Error message here!</span>
                        </p>

                        <p class="fieldset">
                            <input class="full-width has-padding" type="submit" value="Reset password">
                        </p>
                    </form>

                    <p class="cd-form-bottom-message"><a href="#0">Back to log-in</a></p>
                </div> <!-- cd-reset-password -->
                <a href="#0" class="cd-close-form">Close</a>
            </div> <!-- cd-user-modal-container -->
        </div> <!-- cd-user-modal -->
        <!----------------------------- end trying------------------------------------------------>
    </div>
</nav>

<!-- end navbar-------------------------------------------------------------->
<!-- slider-------------------------------------------------------------->
