<?php

include "side_bar.phtml";
?>



<div class="container-fluid">
    <div class="table-responsive">

        <div class="btns-div text-center">
            <button class="btn btn-info"  id="button1">Admins</button>
            <button class="btn btn-info" id="button2">Examiners</button>
            <button class="btn btn-info" id="button3">Members</button>
        </div>



        <div class="content-div1">
            <table  class="main-table text-center table table-bordered ">
                <tr>
                    <td>#ID</td>
                    <td>FullName</td>
                    <td>Username</td>
                    <td>Phone</td>
                    <td>Email</td>
                    <td>Type</td>
                    <td>Registered Date</td>
                    <td>Image</td>
                    <td>Control</td>
                </tr>
                <?php
                if (array_key_exists('admins',$this->view_data)){

                    $table='';

                    foreach ($this->view_data['admins'] as $account) {

                        $table.='<tr class="bel">';
                        $table.=' <td>'.$account["user_id"].'</td>';
                        $table.=' <td >'.$account["full_name"].'</td>';
                        $table.=' <td>'.$account["user_name"].'</td>';
                        $table.=' <td>'.$account["phone"].'</td>';
                        $table.=' <td >'.$account["user_email"].'</td>';
                        $table.=' <td >'.$account["groupName"].'</td>';
                        $table.=' <td >'.$account["user_entry_date"]. '</td>';
                        $table.=' <td><img src="/pictures/' . $account['image'] .'" style="width: 50px;height: 20px"></td>';

                        $table.=" <td><a href='/admin/edit/".$account["user_id"]. "'class='fa fa-edit edit'></a>&nbsp;&nbsp;&nbsp;
                                    <a href='/admin/delete/".$account["user_id"]. "'class='fa fa-trash-o trash'></a>&nbsp;&nbsp;&nbsp;";
//
                        if ($account["user_state"] == 0) {
                            $table.= ' <a href="/admin/active/'.$account["user_id"].'" class=" fa fa-remove non-active"></a></td>';

                        }elseif ($account["user_state"] == 1){
                            $table.='<a href="/admin/nonactive/'.$account["user_id"].'" class="fa fa fa-check-circle actived"></a>';
                        }
                        $table.="</td>";
                        $table.="</tr>";
                    }

                    echo $table;
                }
                ?>
            </table>
        </div>

        <div class="content-div2">
            <table  class="main-table text-center table table-bordered ">
                <tr>
                    <td>#ID</td>
                    <td>FullName</td>
                    <td>Username</td>
                    <td>Phone</td>
                    <td>Email</td>
                    <td>Type</td>
                    <td>Registered Date</td>
                    <td>Image</td>
                    <td>Control</td>
                </tr>
                <?php
                if (array_key_exists('examiners',$this->view_data)){

                    $table='';

                    foreach ($this->view_data['examiners'] as $account) {

                        $table.='<tr class="bel">';
                        $table.=' <td>'.$account["user_id"].'</td>';
                        $table.=' <td >'.$account["full_name"].'</td>';
                        $table.=' <td>'.$account["user_name"].'</td>';
                        $table.=' <td>'.$account["phone"].'</td>';
                        $table.=' <td >'.$account["user_email"].'</td>';
                        $table.=' <td >'.$account["groupName"].'</td>';
                        $table.=' <td >'.$account["user_entry_date"]. '</td>';
                        $table.=' <td><img src="/pictures/' . $account['image'] .'" style="width: 50px;height: 20px"></td>';

//                        $table.=" <td><a href='/admin/edit/".$account["user_id"]. "'class='fa fa-edit edit'></a>&nbsp;&nbsp;&nbsp;
                        $table.="<td><a href='/admin/delete/".$account["user_id"]. "'class='fa fa-trash-o trash'></a>&nbsp;&nbsp;&nbsp;";
//
                        if ($account["user_state"] == 0) {
                            $table.= ' <a href="/admin/active/'.$account["user_id"].'" class="fa fa-remove non-active"></a></td>';

                        }elseif ($account["user_state"] == 1){
                            $table.='<a href="/admin/nonactive/'.$account["user_id"].'" class="fa fa fa-check-circle actived"></a>';
                        }
                        $table.="</td>";
                        $table.="</tr>";
                    }

                    echo $table;
                }
                ?>
            </table>
        </div>

        <div class="content-div3">
            <table  class="main-table text-center table table-bordered ">
                <tr>
                    <td>#ID</td>
                    <td>FullName</td>
                    <td>Username</td>
                    <td>Phone</td>
                    <td>Email</td>
                    <td>Type</td>
                    <td>Registered Date</td>
                    <td>Image</td>
                    <td>Control</td>
                </tr>
                <?php
                if (array_key_exists('members',$this->view_data)){

                    $table='';

                    foreach ($this->view_data['members'] as $account) {

                        $table.='<tr class="bel">';
                        $table.=' <td>'.$account["user_id"].'</td>';
                        $table.=' <td >'.$account["full_name"].'</td>';
                        $table.=' <td>'.$account["user_name"].'</td>';
                        $table.=' <td>'.$account["phone"].'</td>';
                        $table.=' <td >'.$account["user_email"].'</td>';
                        $table.=' <td >'.$account["groupName"].'</td>';
                        $table.=' <td >'.$account["user_entry_date"]. '</td>';
                        $table.=' <td><img src="/pictures/' . $account['image'] .'" style="width: 50px;height: 20px"></td>';

//                        $table.=" <td><a href='/admin/edit/".$account["user_id"]. "'class='fa fa-edit edit'></a>&nbsp;&nbsp;&nbsp;
                        $table.=" <td><a href='/admin/delete/".$account["user_id"]. "'class='fa fa-trash-o trash'></a>&nbsp;&nbsp;&nbsp;";
//
                        if ($account["user_state"] == 0) {
                            $table.= ' <a href="/admin/active/'.$account["user_id"].'" class="fa fa-remove non-active"></a></td>';

                        }elseif ($account["user_state"] == 1){
                            $table.='<a href="/admin/nonactive/'.$account["user_id"].'" class="fa fa fa-check-circle actived"></a>';
                        }
                        $table.="</td>";
                        $table.="</tr>";
                    }

                    echo $table;
                }
                ?>
            </table>
        </div>

    </div>
</div>

