<?php
include "side_bar.phtml";
?>


<h1 class="text-center"> Add New Category </h1>
<div class="container-fluid cat-e">
    <form class="form-horizontal" action="/category/add" method="POST">

        <!-- Start Name Field -->
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                  <label class=" control-label label-edit"> Name </label>
                </div>
                <div class="col-sm-10">
                    <input type="text" name="name" class="form-control input-edit category_name " onkeyup="lettersOnlyTwo(this)" autocomplete="off" required="required" placeholder="Name Of The Categories"/>
                </div>
            </div>
        </div>
        <!-- End Name Field -->

        <!-- Start Description Field -->
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                  <label class="control-label label-edit"> Description </label>
                </div>
                 <div class="col-sm-10">
                      <input type="text" name="description" class="form-control input-edit" placeholder="Describe The Category" />
                 </div>
            </div>
        </div>
        <!-- End Description Field -->



        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label class="control-label label-edit"> Type Of Category </label>
                </div>
                <div class="col-sm-10" id="type_category">
                    <div>
                        <input class="main_cat" type="radio" name="cat" id="cat-main" value="0" onkeyup="lettersOnlyTwo(this)">
                        <label for="cat-main">Main Category</label>
                    </div>

                    <div>
                        <input class="sub_cat" type="radio" name="cat" id="cat-sub" value="0">
                        <label for="cat-sub">Sub Category</label>
                    </div>
                 </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-2">
                <label class=" control-label label-edit"> Choose The Main Category </label>
            </div>
            <div class="col-sm-10">
                <select name="categories" class="categories form-control select-option" onchange="getValueFromOptionToInput(this.value);">
                    <option value=""></option>
                    <?php
                    foreach ($this->view_data['mainCategories'] as $category) {
                        echo "<option value='" . $category['cat_id'] . "'>" . $category['cat_name'] . "</option>";
                    }
                    ?>
                </select>
            </div>
        </div>

        <!-- Start Submit Field -->
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" value="Add Category" class="btn btn-success btn-c" />
            </div>
        </div>
        <!-- End Submit Field -->

    </form>
</div>

