

                <section class="content">

                  <div class="box">
                                                  <div class="box-header">
                                                    <h2 class="card-header info-color white-text text-center py-4">
                                                        <strong>اضافة فئة جديدة</strong>
                                                    </h2>
                                                  </div><!-- /.box-header -->
                                                  <div class="box-body table-responsive">
                  <div class="card">
                      <?php

                      echo Message::check('main');  ?>
                      <div class="row">
                          <span class="title1" style="margin-left:40%;font-size:30px;"><b>Enter Quiz Details</b></span><br /><br />
                          <div class="col-md-3"></div><div class="col-md-6">
                              <form class="form-horizontal title1" name="form" action=""  method="POST">
                                  <fieldset>


                                      <!-- Text input-->
                                      <div class="form-group">
                                          <label class="col-md-12 control-label" for="name"></label>
                                          <div class="col-md-12">
                                              <input id="name" name="name" placeholder="Enter Exam Name" class="form-control input-md" type="text">

                                          </div>
                                      </div>



                                      <!-- Text input-->
                                      <div class="form-group">
                                          <label class="col-md-12 control-label" for="total"></label>
                                          <div class="col-md-12">
                                              <input id="no_q" name="no_q" placeholder="Enter total number of questions" class="form-control input-md" type="number">

                                          </div>
                                      </div>

                                      <!-- Text input-->
                                      <div class="form-group">
                                          <label class="col-md-12 control-label" for="right"></label>
                                          <div class="col-md-12">
                                              <input id="total_mark" name="total_mark" placeholder="Enter total marks of exam" class="form-control input-md" min="0" type="number">

                                          </div>
                                      </div>

                                      <!-- Text input-->
                                      <div class="form-group">
                                          <label class="col-md-12 control-label" for="wrong"></label>
                                          <div class="col-md-12">
                                              <input id="pass_mark" name="pass_mark" placeholder="Enter pass marks of exam" class="form-control input-md" min="0" type="number">

                                          </div>
                                      </div>

                                      <!-- Text input-->
                                      <div class="form-group">
                                          <label class="col-md-12 control-label" for="time"></label>
                                          <div class="col-md-12">
                                              <input id="duration" name="duration" placeholder="Enter time limit for exam in minute" class="form-control input-md" min="1" type="number">

                                          </div>
                                      </div>

                                      <!-- Text input-->
                                      <div class="form-group">
                                          <label class="col-md-12 control-label" for="time"></label>
                                          <div class="col-md-12">
                                              <input id="price" name="price" placeholder="Enter price of exam " class="form-control input-md" min="1" type="number">

                                          </div>
                                      </div>


                                      <!-- Text input-->
                                      <div class="form-group">
                                          <label class="col-md-12 control-label" for="desc"></label>
                                          <div class="col-md-12">
                                              <textarea rows="8" cols="8" name="desc" class="form-control" placeholder="Write description here..."></textarea>
                                          </div>
                                      </div>

                                      <select id="level" name="level" placeholder="Choose correct answer " class="form-control input-md" >
                                          <option value="a">Select level of exam</option>
                                          <option value="h">Hard</option>
                                          <option value="m">medium</option>
                                          <option value="e">Easy</option>
                                      </select>



                                      <div class="form-group">
                                          <label class="col-md-12 control-label" for=""></label>
                                          <div class="col-md-12">
                                              <input  type="submit" style="margin-left:45%" class="btn btn-primary" value="Submit" class="btn btn-primary"/>
                                          </div>
                                      </div>


                                  </fieldset>
                              </form></div>
<!--
                      <form id='newcategory' method='post' action='' enctype='multipart/form-data'>
                          <div class="newArt">

                          <div class="md-form mt-3">
                            <label for="materialContactFormName"><h4> العنوان * </h4></label>
                              <input type="text" name="title" placeholder="Title" id="materialContactFormName" class="form-control"><br><br>

                          </div>
                          <button type="submit" name="submit" class="btn btn-primary" value="submit">اضافة الفئة</button>
                          </div>
                      </form>
                    </div>
                  </div>
                </div>

