<?php
include "side_bar.phtml";
?>
<link rel="stylesheet" type="text/css" href="/layout/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/layout/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/layout/css/backend.css">
<link rel="stylesheet" type="text/css" href="/layout/css/main.css">


<h1 class="text-center"> Add New Category </h1>
<div class="container-fluid">
    <form class="form-horizontal" action="/category/add" method="POST">

        <!-- Start Name Field -->
        <div class="form-group">
            <label class="col-sm-2 control-label label-edit"> Name </label>
            <div class="col-sm-10">
                <input type="text" name="name" class="form-control input-edit" autocomplete="off" required="required" placeholder="Name Of The Categories"/>
            </div>
        </div>
        <!-- End Name Field -->

        <!-- Start Description Field -->
        <div class="form-group">
            <label class="col-sm-2 control-label label-edit"> Description </label>
            <div class="col-sm-10">
                <input type="text" name="description" class="form-control input-edit" placeholder="Describe The Category" />

            </div>
        </div>
        <!-- End Description Field -->



        <!-- Start Ads Field -->
        <div class="form-group">
            <label class="col-sm-2 control-label label-edit"> Type Of Category </label>
            <div class="col-sm-10">

                <div>
                    <input class="main_cat" type="radio" name="cat" id="cat-main" value="0">
                    <label for="cat-main">Main Category</label>
                </div>

                <div>
                    <input class="sub_cat" type="radio" name="cat" id="cat-sub" value="0">
                    <label for="cat-sub">Sub Category</label>
                </div>

            </div>
        </div>
        <!-- End Ads Field -->

        <label class="col-sm-2 control-label label-edit"> Choose The Main Category </label>
        <div class="col-sm-10">
            <select name="categories" class="categories form-control select-option" onchange="getValueFromOptionToInput(this.value);">
                <option value=""></option>
                <?php
                foreach ($this->view_data['categories'] as $category) {
                    echo "<option value='" . $category['cat_id'] . "'>" . $category['cat_name'] . "</option>";
                }
                ?>
            </select>
        </div>

        <!-- Start Submit Field -->
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" value="Add Category" class="btn btn-primary" />
            </div>
        </div>
        <!-- End Submit Field -->

    </form>
</div>

<script src="/layout/js/jquery-2.1.3.min.js"></script>
<script src="/layout/js/bootstrap.min.js"></script>
<script src="/layout/js/backend.js"></script>
<script src="/layout/js/main.js"></script>
