<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>registr for teacher</title>
</head>

<body>
<!--////////////////////////////////////////////////////////////////////////////////////////////////////////////-->
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>

        <div class="col-md-8">

            <form class="form_exam" method="post">
                <div class="row">
                    <div class="col-md-12">
                        <div class="div_name"><h5> Add Exam</h5></div>
                    </div>
                    <?php echo Message::check("logicError"); ?>
                </div>
                <div class="form-group row">
                    <label for="exam_name" class="col-sm-2 col-form-label"> Exam Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputExam_name" name="name">
                    </div>
                    <?php echo Message::check("name"); ?>
                </div>
                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-2 col-form-label">Number of Qu</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" id="inputDateEnd" name="no_q">
                    </div>
                    <?php echo Message::check("no_q"); ?>
                </div>

                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-2 col-form-label">full mark</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" id="inputDateEnd" name="total_mark">
                    </div>
                    <?php echo Message::check("total_mark"); ?>
                </div>
                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-2 col-form-label">pass mark</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" id="inputDateEnd" name="pass_mark">
                    </div>
                    <?php echo Message::check("pass_mark"); ?>
                </div>

                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-2 col-form-label">Enter Time Limit of Exam</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" id="inputDateEnd" name="duration" max="60">
                    </div>
                    <?php echo Message::check("duration"); ?>
                </div>

                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-2 col-form-label">Enter category of Exam</label>
                    <div class="col-sm-10">
                        <select name="category" class="form-control input-md">
                            <?php
                            foreach ($this->view_data["category"] as $row){
                                echo ' <option value="'.$row['cat_id'].'" > '.$row['cat_name'].'';
                            }
                            ?>
                        </select>
                    </div>
                    <?php echo Message::check("category"); ?>
                </div>

                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-2 col-form-label">Price</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" id="inputDateEnd" name="price">
                    </div>
                    <?php echo Message::check("price"); ?>
                </div>

                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-2 col-form-label">Select level of exam</label>
                    <div class="col-sm-10">
                    <select id="level" name="level" placeholder="Choose correct answer " class="form-control input-md" >

                        <option value="h">Hard</option>
                        <option value="m">medium</option>
                        <option value="e" selected>Easy</option>
                    </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-2 col-form-label">Discrption</label>
                    <div class="col-sm-10">
                        <input type="textarea" class="form-control" id="inputDateEnd" name="desc">
                    </div>
                </div>


                <div class="form-group row">
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-primary btn-block">submit</button>
                    </div>
                </div>
            </form>

        </div>
        <div class="col-md-2"></div>


    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
</body>
</html>