
<html>

<head>

</head>

<body>



<div class="row">
<span class="title1" style="margin-left:40%;font-size:30px;"><b>Enter Sample Details</b></span><br /><br />
    <div class="col-md-3"></div><div class="col-md-6">
        <form class="form-horizontal title1" name="form" action=""  method="POST">
<fieldset>


<!-- Text input-->
<div class="form-group">
  <label class="col-md-12 control-label" for="name"></label>  
  <div class="col-md-12">
  <input id="name" name="sample_name" placeholder="Enter Exam Name" class="form-control input-md" type="text">
  </div>
</div>





<div class="form-group">
  <label class="col-md-12 control-label" for=""></label>
  <div class="col-md-12"> 
    <input  type="submit" style="margin-left:45%" class="btn btn-primary" value="Submit" class="btn btn-primary"/>
  </div>
</div>


</fieldset>
</form></div>


</body>
</html>