
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <title>Login/Signup</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" type="text/javascript"></script>
    <link href='https://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://s3-us-west-2.amazonaws.com/s.cdpn.io/148866/reset.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">


</head>
<body>
<!-- partial:index.partial.html -->
<body>
<header role="banner">
    <div id="cd-logo"><a href="#0"><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/148866/cd-logo_1.svg" alt="Logo"></a></div>

    <nav class="main-nav">
        <ul>
            <!-- inser more links here -->
            <li><a class="cd-signin" href="#0">Sign in</a></li>
            <li><a class="cd-signup" href="#0">Sign up</a></li>
        </ul>
    </nav>
</header>
<div class="cd-user-modal"> <!-- this is the entire modal form, including the background -->
    <div class="cd-user-modal-container"> <!-- this is the container wrapper -->
        <ul class="cd-switcher">
            <li><a href="#0">Sign in</a></li>
            <li><a href="#0">New account</a></li>
        </ul>

        <div id="cd-login"> <!-- log in form -->
            <form class="cd-form"  method="post" action="/user/login">

                <p class="fieldset">
                <div class="input-group mb-3">
                    <input class="form-control"  id="signin-email" type="text" name="username" placeholder="  Enter Your Email" >
                    <?php echo Message::check('username');  ?>
                    <div class="input-group-append">
                        <span class="input-group-text" style="background: #ffffff; color: #007bff">@gmail.com</span>
                    </div>
                </div>
                </p>

                <p class="fieldset">
                    <label class="image-replace cd-password" for="signin-password">Password</label>
                    <input class="full-width has-padding has-border" id="signin-password" name="password" type="password"  placeholder="Enter Your Password">
                    <?php echo Message::check('password');  ?>
                    <a href="#0" class="hide-password">Show</a>

                </p>


<!--                <p class="fieldset">-->
<!--                    <input type="checkbox" id="remember-me" checked>-->
<!--                    <label for="remember-me">Remember me</label>-->
<!--                </p>-->

                <p class="fieldset">
                    <button type="submit" class="btn btn-primary" name="login"  value="login"> login</button>
<!--                    <input class="full-width has-padding btn btn-primary" type="submit" name="login" value="login">-->
                </p>
            </form>


<!--            <p class="cd-form-bottom-message"><a href="#0">Forgot your password?</a></p>-->
            <!-- <a href="#0" class="cd-close-form">Close</a> -->
        </div> <!-- cd-login -->

        <div id="cd-signup"> <!-- sign up form -->
            <form class="cd-form" name="regform" id="signupForm" method="post" action="/user/add" enctype="multipart/form-data">

                <div id="preview-container">
                    <div class="text-center">
                        <h4> Your Image Profile </h4>
                        <img class="preview" src="/image/avatar.png"/>
                        <!--  <input type="button" value="Upload" class="upload-image btn-default"/>-->
                        <input id="upload" type="file" name="fileToUpload" accept="image/*"/>
                    </div>
                </div>


                <p class="fieldset">
                <div class="input-group mb-3">
                    <div class="input-group-append">
                        <span class="input-group-text" style="background: #ffffff;"><img src="/image/user.png" width="20px" height="20px"></span>
                    </div>
                    <input class="form-control" id="username" type="text" name="username" onkeyup="lettersOnly(this)" placeholder="   Enter Your UserName" >
                    <?php echo Message::check('username');  ?>
                </div>
                </p>

                <p class="fieldset">
                <div class="input-group mb-3">
                    <div class="input-group-append">
                        <span class="input-group-text" style="background: #ffffff;"><img src="/image/user.png" width="20px" height="20px"></span>
                    </div>
                    <input class="form-control" id="fullname" type="text" name="full_name" onkeyup="lettersOnlyTwo(this)" placeholder="   Enter Your FullName" >
                    <?php echo Message::check('full_name');  ?>
                </div>
                </p>

                <p class="fieldset">
                <div class="input-group mb-3">
                    <div class="input-group-append" >
                        <select style="background: #ffffff; color: #007bff">
                            <option value="+967">+967</option>
                            <option value="+955">+955</option>
                            <option value="+224">+224</option>
                            <option value="+968">+968</option>
                        </select>

                    </div>
                    <input class="form-control" id="phone" type="text" name="phone" onkeyup="numbersOnly(this)" placeholder="   Enter Your Phone" >
                </div>
                <?php echo Message::check('phone');  ?>
                </p>

                <p class="fieldset">
                <div class="input-group mb-3">
                    <input class="form-control" id="email" type="email" name="email" placeholder="  Enter Your Email" >
                    <div class="input-group-append">
<!--                        --><?php //echo Message::check('email');  ?>

                        <span class="input-group-text" style="background: #ffffff; color: #007bff">@gmail.com</span>
                    </div>

                </div>
                </p>

                <p class="fieldset">
                    <label class="image-replace cd-password" for="password">Password</label>
                    <input class="full-width has-padding has-border" id="password" name="password" type="password"  placeholder="Enter Your Password">
                    <a href="#0" class="hide-password">Show</a>
                    <?php echo Message::check('password');  ?>
                </p>

                <p class="fieldset">
                    <label class="image-replace cd-password" for="confirm-password"> Confirm Password</label>
                    <input class="full-width has-padding has-border" id="confirm-password" name="confirm_password" type="password"  placeholder="Confirm Your Password">
                    <a href="#0" class="hide-password">Show</a>
                    <?php echo Message::check('passwordConfirm');  ?>

                </p>

<!--                                <p class="fieldset">-->
<!--                                <p>Register as:</p>-->
<!---->
<!--                                <div class="form-check">-->
<!--                                    <label class="form-check-label" for="radio1">-->
<!--                                        <input type="radio"  id="individual" name="individual" value="Individual" checked> Individual-->
<!--                                    </label>-->
<!--                                </div>-->
<!---->
<!--                                <div class="form-check">-->
<!--                                    <label for="radio2">-->
<!--                                        <input type="radio" id="company" name="company" value="Company"> Company-->
<!--                                    </label>-->
<!--                                </div>-->

<!--                                <div class="form-check">-->
<!--                                    <label for="radio2">-->
<!--                                        <input type="radio" id="teacher" name="teacher" value="Teacher"> Teacher-->
<!--                                    </label>-->
<!--                                </div>-->
                                </p>

                <div class="form-group">
                    <label for="Select" class="col-sm-2 control-label">type user</label>

                    <select id="Select" class="form-control" name="type">
                        <option value="3">User</option>
                        <option value="2">Examiner</option>
                    </select>
                    <?php echo Message::check('type');  ?>
                </div>

                <p class="fieldset">
                    <input type="checkbox" name="terms"  id="accept-terms" required >
                    <label for="accept-terms" >I agree to the <a href="termsPage.php">Terms</a></label>
                </p>



                <p class="fieldset">
                    <button type="submit" class="btn btn-primary" name="submit"  value="register">add user</button>
                </p>
            </form>

            <!-- <a href="#0" class="cd-close-form">Close</a> -->
        </div> <!-- cd-signup -->

        <div id="cd-reset-password"> <!-- reset password form -->
            <p class="cd-form-message">Lost your password? Please enter your email address. You will receive a link to create a new password.</p>

            <form class="cd-form">
                <p class="fieldset">
                    <label class="image-replace cd-email" for="reset-email">E-mail</label>
                    <input class="full-width has-padding has-border" id="reset-email" type="email" placeholder="E-mail">
                    <span class="cd-error-message">Error message here!</span>
                </p>

                <p class="fieldset">
                    <input class="full-width has-padding" type="submit" value="Reset password">
                </p>
            </form>

            <p class="cd-form-bottom-message"><a href="#0">Back to log-in</a></p>
        </div> <!-- cd-reset-password -->
        <a href="#0" class="cd-close-form">Close</a>
    </div> <!-- cd-user-modal-container -->
</div> <!-- cd-user-modal -->




<script>
    $(document).ready(function() {
        $('#signupForm').submit(function() {
            if ($('input:checkbox', this).length == $('input:checked', this).length ) {
                // everything's fine...
            } else {
                alert('Please tick all checkboxes!');
                return false;
            }
        });
    });
</script>
</body>
<!-- partial -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script  src="/js/bootstrap.min.js"></script>
<script  src="/js/jquery-3.3.1.min.js"></script>
<script  src="/js/jquery.validate.js"></script>
<script  src="/js/script.js"></script>

</body>
</html>
