
<?php
include "side_bar.phtml";
?>
<link rel="stylesheet" type="text/css" href="/layout/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/layout/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/layout/css/backend.css">
<link rel="stylesheet" type="text/css" href="/layout/css/main.css">

<h1 class="text-center"> Manage Categories </h1>
<div class="container-fluid">
    <div class="table-responsive">
        <table class="main-table text-center table table-bordered">
            <tr>
                <td>#ID</td>
                <td>Name</td>
                <td>Created By</td>
                <td>Created At</td>
                <td>Updated By</td>
                <td>Updated At</td>
                <td>Control</td>
            </tr>
            <?php
            if (array_key_exists('categories',$this->view_data)){

                $table='';

                foreach ($this->view_data['categories'] as $category) {


                    $table.='<tr class="bel">';
                    $table.=' <td>'.$category["cat_id"].'</td>';
                    $table.=' <td >'.$category["cat_name"].'</td>';
                    $table.=' <td>'.$category["user_id"].'</td>';
                    $table.=' <td>'.$category["cat_created_at"].'</td>';
                    $table.=' <td >'.$category["user_id"].'</td>';
                    $table.=' <td >'.$category["cat_updated_at"].'</td>';

                    $table.=" <td><a href='/user/edit/".$category["cat_id"]. "'class='glyphicon glyphicon-edit edit'></a>&nbsp;&nbsp;&nbsp;
                                            <a href='/user/delete/".$category["cat_id"]. "'class='glyphicon glyphicon-trash trash'></a>&nbsp;&nbsp;&nbsp;";
//
                    if ($category["cat_state"] == 0) {
                        $table.= ' <a href="/user/active/'.$category["cat_id"].'" class=" glyphicon glyphicon-remove-sign non-active"></a></td>';

                    }elseif ($category["cat_state"] == 1){
                        $table.='<a href="/user/nonactive/'.$category["cat_id"].'" class="glyphicon glyphicon-ok-sign actived"></a>';
                    }

                    $table.="</td>";
                    $table.="</tr>";

                }

                echo $table;
            }
            ?>
        </table>
    </div>
</div>

<script src="/layout/js/jquery-2.1.3.min.js"></script>
<script src="/layout/js/bootstrap.min.js"></script>
<script src="/layout/js/backend.js"></script>
<script src="/layout/js/main.js"></script>