
<?php
include "side_bar.phtml";
?>
<link rel="icon" href="images/logo.png" type="image/png" sizes="16x16">
<link rel="stylesheet" type="text/css" href="/layout/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/layout/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/layout/css/backend.css">
<link rel="stylesheet" type="text/css" href="/layout/css/main.css">

<h1 class="text-center"> Manage Categories</h1>
<div class="container-fluid">
    <div class="table-responsive">
        <table class="main-table text-center table table-bordered">
            <tr>
                <td>#ID</td>
                <td>Name</td>
                <td>Created By</td>
                <td>Created At</td>
                <td>Updated By</td>
                <td>Updated At</td>
                <td>Control</td>
            </tr>
            <?php
            if (array_key_exists('cates',$this->view_data)){
                foreach ($this->view_data['cates'] as $category) {


                    echo '<tr class="bel">';
                    echo ' <td>'.$category["cat_id"].'</td>';
                    echo ' <td >'.$category["cat_name"].'</td>';
                    echo ' <td>'.$category["Created_By"].'</td>';
                    echo ' <td>'.$category["cat_created_at"].'</td>';
                    echo ' <td>'.$category["Created_By"].'</td>';
                    echo ' <td >'.$category["cat_updated_at"].'</td>';

                   echo " <td><a href='/category/edit/".$category["cat_id"]. "'class='glyphicon glyphicon-edit edit'></a>&nbsp;&nbsp;&nbsp;
                                            <a href='/category/delete/".$category["cat_id"]. "'class='glyphicon glyphicon-trash cat-trash'></a>&nbsp;&nbsp;&nbsp;";
//
                    if ($category["cat_state"] == 0) {
                        echo  ' <a href="/category/active/'.$category["cat_id"].'" class=" glyphicon glyphicon-remove-sign cat-non-active"></a></td>';

                    }elseif ($category["cat_state"] == 1){
                        echo '<a href="/category/nonactive/'.$category["cat_id"].'" class="glyphicon glyphicon-ok-sign cat-actived"></a>';
                    }

                    echo "</td>";
                    echo "</tr>";

                }
            }

            ?>
        </table>
    </div>
    <a href="/category/add/" class="btn btn-info btn-block"><i class="glyphicon glyphicon-plus"></i> Add New Category</a>
</div>

