<?php
include "side_bar.php";

//include "init.php";

?>
<link rel="stylesheet" type="text/css" href="/layout/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/layout/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/layout/css/backend.css">
<link rel="stylesheet" type="text/css" href="/layout/css/main.css">

    <div class="container-fluid home-stats text-center">
        <h1>cPanel</h1>

        <div class="row">
            <div class="col-md-3">
                <a href="members.php">
                    <div class="stat stat-members">
<!--                        <i class="fa fa-users"></i>-->
                                                    <img src="layout/images/user.png" width="60px" height="60px">
                        <div class="info">
                            Total Users
                            <span>10
                            </span>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-md-3">
                <a href="members.php?do=Manage&page=Pending">
                    <div class="stat stat-pending">
                        <i class="fa fa-user-plus"></i>
                        <!--                            <img src="layout/images/userPending.png" width="60px" height="60px">-->
                        <div class="info">
                            Pend Users
                            <span>
                          10
                           </span>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-md-3">
                <div class="stat stat-items">
                    <i class="glyphicon glyphicon-signal"></i>
                    <div class="info">
                        Companies
                        <span>3</span>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="stat stat-comments">
                    <i class="glyphicon glyphicon-signal"></i>
                    <div class="info">
                        Statistics
                        <span></span>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <section class="admins">
        <div class="container-fluid">
            <div class="row">
                <table class="table" border="1">
                    <thead>
                    <tr class="table-title">
                        <th class="text-center" scope="col">Admins</th>
                        <th class="text-center" scope="col">Examiner</th>
                        <th class="text-center" scope="col">Members</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr class="table-data">
                        <td>
                            <div class="box">
                                <div class="admin">
                                    <a href='#' class='glyphicon glyphicon-edit edit  pull-right'></a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href='#' class='glyphicon glyphicon-trash trash  pull-right'></a>&nbsp;
                                    <a href='#' class='glyphicon glyphicon glyphicon-remove-sign non-active  pull-right'></a>&nbsp;
                                    <div class="img">
                                        <img class="img-responsive" src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148906966/small/1501685402/enhance" alt="admin">
                                    </div>
                                    <div class="info">
                                        <h3>Joge Lucky</h3>
                                        <p>Lorem ipsum dolor sit amet.</p>
                                    </div>
                                </div>
                            </div>
                        </td>

                        <td>
                            <div class="box">
                                <div class="admin">
                                    <a href='#' class='glyphicon glyphicon-edit edit  pull-right'></a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href='#' class='glyphicon glyphicon-trash trash  pull-right'></a>&nbsp;
                                    <a href='#' class='glyphicon glyphicon glyphicon-remove-sign non-active  pull-right'></a>&nbsp;
                                    <div class="img">
                                        <img class="img-responsive" src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148907137/small/1501685404/enhance" alt="admin">
                                    </div>
                                    <div class="info">
                                        <h3>Joge Lucky</h3>
                                        <p>Lorem ipsum dolor sit amet.</p>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="box">
                                <div class="admin">
                                    <a href='#' class='glyphicon glyphicon-edit edit  pull-right'></a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href='#' class='glyphicon glyphicon-trash trash  pull-right'></a>&nbsp;
                                    <a href='#' class='glyphicon glyphicon glyphicon-remove-sign non-active  pull-right'></a>&nbsp;
                                    <div class="img">
                                        <img class="img-responsive" src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148907019/small/1501685403/enhance" alt="admin">
                                    </div>
                                    <div class="info">
                                        <h3>Joge Lucky</h3>
                                        <p>Lorem ipsum dolor sit amet.</p>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <div class="box">
                                <div class="admin">
                                    <a href='#' class='glyphicon glyphicon-edit edit  pull-right'></a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href='#' class='glyphicon glyphicon-trash trash  pull-right'></a>&nbsp;
                                    <a href='#' class='glyphicon glyphicon glyphicon-remove-sign non-active  pull-right'></a>&nbsp;
                                    <div class="img">
                                        <img class="img-responsive" src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148906966/small/1501685402/enhance" alt="admin">
                                    </div>
                                    <div class="info">
                                        <h3>Joge Lucky</h3>
                                        <p>Lorem ipsum dolor sit amet.</p>
                                    </div>
                                </div>
                            </div>
                        </td>

                        <td>
                            <div class="box">
                                <div class="admin">
                                    <a href='#' class='glyphicon glyphicon-edit edit  pull-right'></a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href='#' class='glyphicon glyphicon-trash trash  pull-right'></a>&nbsp;
                                    <a href='#' class='glyphicon glyphicon glyphicon-remove-sign non-active  pull-right'></a>&nbsp;
                                    <div class="img">
                                        <img class="img-responsive" src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148907137/small/1501685404/enhance" alt="admin">
                                    </div>
                                    <div class="info">
                                        <h3>Joge Lucky</h3>
                                        <p>Lorem ipsum dolor sit amet.</p>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="box">
                                <div class="admin">
                                    <a href='#' class='glyphicon glyphicon-edit edit  pull-right'></a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href='#' class='glyphicon glyphicon-trash trash  pull-right'></a>&nbsp;
                                    <a href='#' class='glyphicon glyphicon glyphicon-remove-sign non-active  pull-right'></a>&nbsp;
                                    <div class="img">
                                        <img class="img-responsive" src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148907019/small/1501685403/enhance" alt="admin">
                                    </div>
                                    <div class="info">
                                        <h3>Joge Lucky</h3>
                                        <p>Lorem ipsum dolor sit amet.</p>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <div class="box">
                                <div class="admin">
                                    <a href='#' class='glyphicon glyphicon-edit edit  pull-right'></a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href='#' class='glyphicon glyphicon-trash trash  pull-right'></a>&nbsp;
                                    <a href='#' class='glyphicon glyphicon glyphicon-remove-sign non-active  pull-right'></a>&nbsp;
                                    <div class="img">
                                        <img class="img-responsive" src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148906966/small/1501685402/enhance" alt="admin">
                                    </div>
                                    <div class="info">
                                        <h3>Joge Lucky</h3>
                                        <p>Lorem ipsum dolor sit amet.</p>
                                    </div>
                                </div>
                            </div>
                        </td>

                        <td>
                            <div class="box">
                                <div class="admin">
                                    <a href='#' class='glyphicon glyphicon-edit edit  pull-right'></a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href='#' class='glyphicon glyphicon-trash trash  pull-right'></a>&nbsp;
                                    <a href='#' class='glyphicon glyphicon glyphicon-remove-sign non-active  pull-right'></a>&nbsp;
                                    <div class="img">
                                        <img class="img-responsive" src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148907137/small/1501685404/enhance" alt="admin">
                                    </div>
                                    <div class="info">
                                        <h3>Joge Lucky</h3>
                                        <p>Lorem ipsum dolor sit amet.</p>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="box">
                                <div class="admin">
                                    <a href='#' class='glyphicon glyphicon-edit edit  pull-right'></a>&nbsp;&nbsp;&nbsp;&nbsp;
                                    <a href='#' class='glyphicon glyphicon-trash trash  pull-right'></a>&nbsp;
                                    <a href='#' class='glyphicon glyphicon glyphicon-remove-sign non-active  pull-right'></a>&nbsp;
                                    <div class="img">
                                        <img class="img-responsive" src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148907019/small/1501685403/enhance" alt="admin">
                                    </div>
                                    <div class="info">
                                        <h3>Joge Lucky</h3>
                                        <p>Lorem ipsum dolor sit amet.</p>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </section>

<script src="/layout/js/jquery-2.1.3.min.js"></script>
<script src="/layout/js/bootstrap.min.js"></script>
<script src="/layout/js/backend.js"></script>
<script src="/layout/js/main.js"></script>