<?php
include "side_bar.phtml";
?>
<section class='statis text-center'>
    <div class="container-fluid">
<!--        <h1>cPanel</h1>-->

        <div class="row">
            <div class="col-md-3">
                <a href="/admin/member" class="four-div">
                    <div class="box bg-primary">
                        <i class="fa fa-users"></i>
                        <h3><?php
                        $countUsers = new Admin();
                        echo $countUsers->countAllUsers();
                            ?></h3>
                        <p class="lead">User registered</p>
                    </div>
                </a>
            </div>
            <div class="col-md-3">
                <a href="/admin/memberPending" class="four-div">
                    <div class="box danger">
                        <i class="fa fa-user-plus"></i>
                        <h3><?php
                            $countUsers = new Admin();
                            echo $countUsers->countAllPendingUsers();
                            ?></h3>
                        <p class="lead">User Pending</p>
                    </div>
                </a>
            </div>
            <div class="col-md-3">
                <a href="#" class="four-div">
                    <div class="box warning">
                        <i class="fa fa-home"></i>
                        <h3>5,154</h3>
                        <p class="lead">Product sales</p>
                    </div>
                </a>
            </div>
            <div class="col-md-3">
                <a href="#" class="four-div">
                    <div class="box success">
                        <i class="fa fa-signal"></i>
                        <h3>5,154</h3>
                        <p class="lead">Transactions</p>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>




<!--    <section class="admins">-->
<!--        <div class="container-fluid">-->
<!--            <div class="row">-->
<!--                <table class="table" border="1">-->
<!--                    <thead>-->
<!--                    <tr class="table-title">-->
<!--                        <th class="text-center" scope="col">Admins</th>-->
<!--                        <th class="text-center" scope="col">Examiner</th>-->
<!--                        <th class="text-center" scope="col">Members</th>-->
<!--                    </tr>-->
<!--                    </thead>-->
<!---->
<!--                </table>-->
<!--            </div>-->
<!--        </div>-->
<!--    </section>-->

