<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Error 404</title>
  <link rel="stylesheet" href="/layout/css/errorPageStyle.css">

</head>
<body>
<!-- partial:index.partial.html -->
<div id="clouds">
            <div class="cloud x1"></div>
            <div class="cloud x1_5"></div>
            <div class="cloud x2"></div>
            <div class="cloud x3"></div>
            <div class="cloud x4"></div>
            <div class="cloud x5"></div>
        </div>
        <div class='c'>
            <div class='_404'>404</div>
            <hr>
            <div class='_1'>THE PAGE</div>
            <div class='_2'>WAS NOT FOUND</div>
            <a class='btnE' href='/admin'>BACK TO LOGIN</a>
        </div>
<!-- partial -->

</body>
</html>
