<?php
include "header.phtml";
?>
<body>


    <div class="slider">



    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel" >
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" >
            <div class="carousel-item active" >
                <img src="/static/img/1.jpeg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>First slide label</h5>
                    <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                    <a href="#work">Check Our Work</a>
                </div>
            </div>
            <div class="carousel-item">
                <img src="/static/img/1.jpeg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Second slide label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="/static/img/1.jpeg "class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Third slide label</h5>
                    <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

</div>




<!-- end slider-------------------------------------------------------------->

    <div class="container">
        <center> <h2>Our  students</h2></center>


        <section class="best_student slider ">
            <div class="row" >

                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student1</h5>
                    </div>
                </div>

                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student2</h5>
                    </div>
                </div>


                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student3</h5>
                    </div>
                </div>


                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student4</h5>
                    </div>
                </div>


                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student5</h5>
                    </div>
                </div>

                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student6</h5>
                    </div>
                </div>

                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student7</h5>
                    </div>
                </div>


                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student8</h5>
                    </div>
                </div>

                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student9</h5>
                    </div>
                </div>

                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student10</h5>
                    </div>
                </div>


                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student11</h5>
                    </div>
                </div>


                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student12</h5>
                    </div>
                </div>




            </div>
        </section>
    </div>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <p>&copy; 2020 By
                    <a href="#"> ability lab</a>
                </p>
            </div>
            <div class="col-xs-12 col-sm-6 text-right">
                <a href="#">
                    <i class="fa fa-facebook"></i>
                </a>
                <a href="#">
                    <i class="fa fa-instagram"></i>
                </a>
                <a href="#">
                    <i class="fa fa-twitter"></i>
                </a>
                <a href="#">
                    <i class="fa fa-youtube"></i>
                </a>
            </div>
        </div>
    </div>
</footer>



















<div class="container">
    <center> <h2> clases</h2></center>
    <div class="row">

        <div class=" col-md-4 col-sm-6">
            <div class="card">
                <img src="/static/img/1.jpeg" >
                <div class="card-text">
                    <h3> plqiess</h3>
                    <h5>Designer</h5>

                </div>
            </div>
        </div>
        <div class=" col-md-4 col-sm-6">
            <div class="card">
                <img src="/static/img/1.jpeg">
                <div class="card-text">
                    <h3> plqiess</h3>
                    <h5>Designer</h5>

                </div>
            </div>
        </div>
        <div class=" col-md-4 col-sm-6">
            <div class="card">
                <img src="/static/img/1.jpeg">
                <div class="card-text">
                    <h3> plqiess</h3>
                    <h5>Designer</h5>

                </div>
            </div>
        </div>
        <div class=" col-md-4 col-sm-6">
            <div class="card">
                <img src="/static/img/1.jpeg">
                <div class="card-text">
                    <h3> plqiess</h3>
                    <h5>Designer</h5>

                </div>
            </div>
        </div>
        <div class=" col-md-4 col-sm-6">
            <div class="card">
                <img src="/static/img/1.jpeg">
                <div class="card-text">
                    <h3> plqiess</h3>
                    <h5>Designer</h5>

                </div>
            </div>
        </div>
        <div class=" col-md-4 col-sm-6">
            <div class="card">
                <img src="/static/img/1.jpeg">
                <div class="card-text">
                    <h3> plqiess</h3>
                    <h5>Designer</h5>

                </div>
            </div>
        </div>
    </div>
</div>



<?php

include "footer.phtml";

