<?php
include "header.phtml";
?>
<body>
<nav class="navbar navbar-expand-lg ">

    <a class="navbar-brand" href="#"><img src="/static/img/logo.png"  width="70px" class="rounded-circle" style="margin-bottom: 18px;"></a>
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>

        <!----------------------------- start trying---------------------------------------------->

        <nav class="main-nav">
            <ul>
                <!-- inser more links here -->
                <li><a class="btn btn-outline-success my-2 my-sm-0" href="#0" style=" color:green; margin-right: 10px; padding: 10px;">Sign in</a></li>
                <li><a class="btn btn-outline-success my-2 my-sm-0" href="#0" style=" color:green; margin-right: 10px; padding: 10px;">Sign up</a></li>
            </ul>
        </nav>
        <div class="cd-user-modal"> <!-- this is the entire modal form, including the background -->
            <div class="cd-user-modal-container"> <!-- this is the container wrapper -->
                <ul class="cd-switcher">
                    <li><a href="#0">Sign in</a></li>
                    <li><a href="#0">New account</a></li>
                </ul>

                <div id="cd-login"> <!-- log in form -->
                    <form class="cd-form"  method="post" action="/user/login">

                        <p class="fieldset">
                        <div class="input-group mb-3">
                            <input class="form-control"  id="signin-email" type="text" name="username" placeholder="  Enter Your Email" >
                            <?php echo Message::check('username');  ?>
                            <div class="input-group-append">
                                <span class="input-group-text" style="background: #ffffff; color: #007bff">@gmail.com</span>
                            </div>
                        </div>
                        </p>

                        <p class="fieldset">
                            <label class="image-replace cd-password" for="signin-password">Password</label>
                            <input class="full-width has-padding has-border" id="signin-password" name="password" type="password"  placeholder="Enter Your Password">
                            <?php echo Message::check('password');  ?>
                            <a href="#0" class="hide-password">Show</a>

                        </p>


                        <!--                <p class="fieldset">-->
                        <!--                    <input type="checkbox" id="remember-me" checked>-->
                        <!--                    <label for="remember-me">Remember me</label>-->
                        <!--                </p>-->

                        <p class="fieldset">
                            <button type="submit" class="btn btn-primary" name="login"  value="login"> login</button>
                            <!--                    <input class="full-width has-padding btn btn-primary" type="submit" name="login" value="login">-->
                        </p>
                    </form>


                    <!--            <p class="cd-form-bottom-message"><a href="#0">Forgot your password?</a></p>-->
                    <!-- <a href="#0" class="cd-close-form">Close</a> -->
                </div> <!-- cd-login -->

                <div id="cd-signup"> <!-- sign up form -->
                    <form class="cd-form" name="regform" id="signupForm" method="post" action="/user/add" enctype="multipart/form-data">

                        <div id="preview-container">
                            <div class="text-center">
                                <h4> Your Image Profile </h4>
                                <img class="preview" src="/image/avatar.png"/>
                                <!--  <input type="button" value="Upload" class="upload-image btn-default"/>-->
                                <input id="upload" type="file" name="fileToUpload" accept="image/*"/>
                            </div>
                        </div>


                        <p class="fieldset">
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text" style="background: #ffffff;"><img src="/image/user.png" width="20px" height="20px"></span>
                            </div>
                            <input class="form-control" id="username" type="text" name="username" onkeyup="lettersOnly(this)" placeholder="   Enter Your UserName" >
                            <?php echo Message::check('username');  ?>
                        </div>
                        </p>

                        <p class="fieldset">
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text" style="background: #ffffff;"><img src="/image/user.png" width="20px" height="20px"></span>
                            </div>
                            <input class="form-control" id="fullname" type="text" name="full_name" onkeyup="lettersOnlyTwo(this)" placeholder="   Enter Your FullName" >
                            <?php echo Message::check('full_name');  ?>
                        </div>
                        </p>

                        <p class="fieldset">
                        <div class="input-group mb-3">
                            <div class="input-group-append" >
                                <select style="background: #ffffff; color: #007bff">
                                    <option value="+967">+967</option>
                                    <option value="+955">+955</option>
                                    <option value="+224">+224</option>
                                    <option value="+968">+968</option>
                                </select>

                            </div>
                            <input class="form-control" id="phone" type="text" name="phone" onkeyup="numbersOnly(this)" placeholder="   Enter Your Phone" >
                        </div>
                        <?php echo Message::check('phone');  ?>
                        </p>

                        <p class="fieldset">
                        <div class="input-group mb-3">
                            <input class="form-control" id="email" type="email" name="email" placeholder="  Enter Your Email" >
                            <div class="input-group-append">
                                <!--                        --><?php //echo Message::check('email');  ?>

                                <span class="input-group-text" style="background: #ffffff; color: #007bff">@gmail.com</span>
                            </div>

                        </div>
                        </p>

                        <p class="fieldset">
                            <label class="image-replace cd-password" for="password">Password</label>
                            <input class="full-width has-padding has-border" id="password" name="password" type="password"  placeholder="Enter Your Password">
                            <a href="#0" class="hide-password">Show</a>
                            <?php echo Message::check('password');  ?>
                        </p>

                        <p class="fieldset">
                            <label class="image-replace cd-password" for="confirm-password"> Confirm Password</label>
                            <input class="full-width has-padding has-border" id="confirm-password" name="confirm_password" type="password"  placeholder="Confirm Your Password">
                            <a href="#0" class="hide-password">Show</a>
                            <?php echo Message::check('passwordConfirm');  ?>

                        </p>

                        <!--                                <p class="fieldset">-->
                        <!--                                <p>Register as:</p>-->
                        <!---->
                        <!--                                <div class="form-check">-->
                        <!--                                    <label class="form-check-label" for="radio1">-->
                        <!--                                        <input type="radio"  id="individual" name="individual" value="Individual" checked> Individual-->
                        <!--                                    </label>-->
                        <!--                                </div>-->
                        <!---->
                        <!--                                <div class="form-check">-->
                        <!--                                    <label for="radio2">-->
                        <!--                                        <input type="radio" id="company" name="company" value="Company"> Company-->
                        <!--                                    </label>-->
                        <!--                                </div>-->

                        <!--                                <div class="form-check">-->
                        <!--                                    <label for="radio2">-->
                        <!--                                        <input type="radio" id="teacher" name="teacher" value="Teacher"> Teacher-->
                        <!--                                    </label>-->
                        <!--                                </div>-->
                        </p>

                        <div class="form-group">
                            <label for="Select" class="col-sm-2 control-label">type user</label>

                            <select id="Select" class="form-control" name="type">
                                <option value="3">User</option>
                                <option value="2">Examiner</option>
                            </select>
                            <?php echo Message::check('type');  ?>
                        </div>

                        <p class="fieldset">
                            <input type="checkbox" name="terms"  id="accept-terms" required >
                            <label for="accept-terms" >I agree to the <a href="termsPage.php">Terms</a></label>
                        </p>



                        <p class="fieldset">
                            <button type="submit" class="btn btn-primary" name="submit"  value="register">add user</button>
                        </p>
                    </form>

                    <!-- <a href="#0" class="cd-close-form">Close</a> -->
                </div> <!-- cd-signup -->

                <div id="cd-reset-password"> <!-- reset password form -->
                    <p class="cd-form-message">Lost your password? Please enter your email address. You will receive a link to create a new password.</p>

                    <form class="cd-form">
                        <p class="fieldset">
                            <label class="image-replace cd-email" for="reset-email">E-mail</label>
                            <input class="full-width has-padding has-border" id="reset-email" type="email" placeholder="E-mail">
                            <span class="cd-error-message">Error message here!</span>
                        </p>

                        <p class="fieldset">
                            <input class="full-width has-padding" type="submit" value="Reset password">
                        </p>
                    </form>

                    <p class="cd-form-bottom-message"><a href="#0">Back to log-in</a></p>
                </div> <!-- cd-reset-password -->
                <a href="#0" class="cd-close-form">Close</a>
            </div> <!-- cd-user-modal-container -->
        </div> <!-- cd-user-modal -->
        <!----------------------------- end trying------------------------------------------------>

    </div>
</nav>

    <div class="slider">



    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel" >
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" >
            <div class="carousel-item active" >
                <img src="/static/img/1.jpeg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>First slide label</h5>
                    <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                    <a href="#work">Check Our Work</a>
                </div>
            </div>
            <div class="carousel-item">
                <img src="/static/img/1.jpeg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Second slide label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="/static/img/1.jpeg "class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Third slide label</h5>
                    <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

</div>




<!-- end slider-------------------------------------------------------------->

    <div class="container">
        <center> <h2>Our  students</h2></center>


        <section class="best_student slider ">
            <div class="row" >

                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student1</h5>
                    </div>
                </div>

                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student2</h5>
                    </div>
                </div>


                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student3</h5>
                    </div>
                </div>


                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student4</h5>
                    </div>
                </div>


                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student5</h5>
                    </div>
                </div>

                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student6</h5>
                    </div>
                </div>

                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student7</h5>
                    </div>
                </div>


                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student8</h5>
                    </div>
                </div>

                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student9</h5>
                    </div>
                </div>

                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student10</h5>
                    </div>
                </div>


                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student11</h5>
                    </div>
                </div>


                <div class="col-lg-1 col-sm-3 col-6">
                    <div class="slide">
                        <img src="/./static/img/2.jpeg">
                        <h5 >student12</h5>
                    </div>
                </div>



            </div>
        </section>
    </div>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6">
                <p>&copy; 2020 By
                    <a href="#"> ability lab</a>
                </p>
            </div>
            <div class="col-xs-12 col-sm-6 text-right">
                <a href="#">
                    <i class="fa fa-facebook"></i>
                </a>
                <a href="#">
                    <i class="fa fa-instagram"></i>
                </a>
                <a href="#">
                    <i class="fa fa-twitter"></i>
                </a>
                <a href="#">
                    <i class="fa fa-youtube"></i>
                </a>
            </div>
        </div>
    </div>
</footer>




















<div class="container">
    <center> <h2> clases</h2></center>
    <div class="row">

        <div class=" col-md-4 col-sm-6">
            <div class="card">
                <img src="/static/img/1.jpeg" >
                <div class="card-text">
                    <h3> plqiess</h3>
                    <h5>Designer</h5>

                </div>
            </div>
        </div>
        <div class=" col-md-4 col-sm-6">
            <div class="card">
                <img src="/static/img/1.jpeg">
                <div class="card-text">
                    <h3> plqiess</h3>
                    <h5>Designer</h5>

                </div>
            </div>
        </div>
        <div class=" col-md-4 col-sm-6">
            <div class="card">
                <img src="/static/img/1.jpeg">
                <div class="card-text">
                    <h3> plqiess</h3>
                    <h5>Designer</h5>

                </div>
            </div>
        </div>
        <div class=" col-md-4 col-sm-6">
            <div class="card">
                <img src="/static/img/1.jpeg">
                <div class="card-text">
                    <h3> plqiess</h3>
                    <h5>Designer</h5>

                </div>
            </div>
        </div>
        <div class=" col-md-4 col-sm-6">
            <div class="card">
                <img src="/static/img/1.jpeg">
                <div class="card-text">
                    <h3> plqiess</h3>
                    <h5>Designer</h5>

                </div>
            </div>
        </div>
        <div class=" col-md-4 col-sm-6">
            <div class="card">
                <img src="/static/img/1.jpeg">
                <div class="card-text">
                    <h3> plqiess</h3>
                    <h5>Designer</h5>

                </div>
            </div>
        </div>
    </div>
</div>



<?php
include "footer.phtml";