
<form action="" method="post">
<div class="form-group">
    <label for="exampleInputEmail1">username</label>
    <input type="text" class="form-control"  name="username">
    <?php echo Message::check('username');  ?>
</div>
<div class="form-group">
    <label for="exampleInputPassword1">password:</label>
    <input type="password" class="form-control"  name="password">
    <?php echo Message::check('password');  ?>
</div>

<button type="submit" class="btn btn-primary" name="login"  value="login"> login</button>

</form>