<link rel="stylesheet" type="text/css" href="/layout/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/layout/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/layout/css/backend.css">
<link rel="stylesheet" type="text/css" href="/layout/css/main.css">



<form class="login" action="/admin/login" method="POST">


    <div class="login-div">
        <div class="text-center">
            <img src="/images/logo.png" class="logo" width="100px" height="100px">
        </div>

        <h3 class="text-center">Admin Login</h3>

        <label for="exampleInputEmail1">username</label>
        <input type="text" class="form-control"  name="username" placeholder="Username" autocomplete="off">
        <?php echo Message::check('username');  ?>

        <label for="exampleInputPassword1">password:</label>
        <input type="password" class="form-control"  name="password" placeholder="Password"  autocomplete="new-password">
        <?php echo Message::check('password');  ?>

        <button type="submit" class="btn btn-primary btn-block" name="login"  value="login"> login</button>
    </div>
</form>
