<?php Session::logged();?>
<div id="contents">
    <?php include "init.php"?>
    <title><?php getTitle();?></title>
    <link rel="icon" href="images/logo.png" type="image/png" sizes="16x16">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/fontawesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="/layout/css/backend.css">
    <link rel="stylesheet" type="text/css" href="/layout/css/main.css">

<!------------------------------------------ Start-->

    <nav class="navbar navbar-inverse navbar-expand-lg">
        <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class="b"><a href="#" class="nav-item text-center"><i data-show="show-side-navigation1" class="fa fa-align-left show-side-btn" style="font-size: 22px;"></i></a></li>
        </ul>
            <!--        <a class="navbar-brand" href="#"><img src="/images/logo.png" width="50px" height="50px"></a>-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="fa fa-align-center show-side-btn" style="color: #ffffff;"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <center>
            <ul class="nav navbar-nav">

                <li class="n n1"><a class="nav-item1 active" href="/admin/dashboard"><i class="fa fa-home"  style="font-size: 22px;"></i> </br><?php echo lang('HOME_ADMIN')?></a></li>
                <li class="n n2"><a class="nav-item2" href="/admin/category"><i class="fa fa-th" style="font-size: 22px;"></i></br><?php echo lang('CATEGORIES')?></a></li>
                <li class="n n3"><a class="nav-item3" href="#"><i class="fa fa-star"  style="font-size: 22px;"></i></br><?php echo lang('STARS')?></a></li>
                <li class="n n4"><a class="nav-item4" href="/admin/member"><i class="fa fa-users"  style="font-size: 22px;"></i></br><?php echo lang('MEMBERS')?></a></li>
                <li class="n n5"><a class="nav-item5" href="#"><i class="fa fa-info-circle"  style="font-size: 22px;"></i></br><?php echo lang('ABOUT_US')?></a></li>
                <li class="n n6"><a class="nav-item6" href="#"><i class="fa fa-signal"  style="font-size: 22px;"></i></br><?php echo lang('STATISTICS')?></a></li>
                <li class="n n7"><a class="nav-item7" href="/exam/exama"><i class="fa fa-signal"  style="font-size: 22px;"></i></br>Exam</a></li>
<!--                <li><a class="nav-item text-center" href="#"><i class="fa fa-comment" style="font-size: 18px;"></i><span>23</span></a></li>-->
                <li class="n n8"><a class="nav-item8" href="#"><i class="fa fa-bell" style="font-size: 22px;"></i>98</a></li>

                <li class="dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <?php
                        if (array_key_exists('admins',$this->view_data)) {
                            foreach ($this->view_data['admins'] as $admin) {
                                if ($admin['user_id'] == Session::logged()) {
                                    echo $admin['user_name'];
                                }
                            }
                        } else {
                            echo "error";
                        }

                        ?>
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li class="d1"><a class="da1" href="/user/edit/"><i class="fa fa-edit"></i> Edit Profile </a></li>
                        <li class="d2"><a class="da2" href="#"><i class="fa fa-cog"></i> Settings </a></li>
                        <li class="d3"><a class="da3" href="/admin/logout"><i class="fa fa-sign-out"></i> Logout </a></li>
                    </ul>
                </li>
            </ul>
            </center>
        </div>
        </div>
    </nav>

    <aside class="side-nav" id="show-side-navigation1">
        <i class="fa fa-align-right close-aside hidden-sm hidden-md hidden-lg" data-close="show-side-navigation1"></i>
        <div class="heading">
            <img src="https://uniim1.shutterfly.com/ng/services/mediarender/THISLIFE/021036514417/media/23148907008/medium/1501685726/enhance" alt="">
            <div class="info">
                <h3><a href="#"><?php
                        if (array_key_exists('admins',$this->view_data)) {
                            foreach ($this->view_data['admins'] as $admin) {
                                if ($admin['user_id'] == Session::logged()) {
                                    echo $admin['full_name'];
                                }
                            }
                        } else {
                            echo "error";
                        }

                        ?></a></h3>
                <p>Lorem ipsum dolor sit amet consectetur.</p>
            </div>
        </div>
        <div class="search">
            <input type="text" placeholder="Type here"><i class="fa fa-search"></i>
        </div>
        <ul class="categories">
            <li><i class="fa fa-home fa-fw" aria-hidden="true"></i><a data-toggle="collapse" href="#about"> About us</a>
                <div class="collapse" id="about">
                    <a href="#">Lorem ipsum</a><br>
                    <a href="#">ipsum dolor</a><br>
                    <a href="#">dolor ipsum</a><br>
                    <a href="#">amet consectetur</a><br>
                    <a href="#">ipsum dolor sit</a><br>
                </div>
            </li>
            <li><i class="fa fa-support fa-fw"></i><a data-toggle="collapse" href="#subscribe-us"> Subscribe us</a>
                <div class="collapse" id="subscribe-us">
                    <a href="#">Lorem ipsum</a><br>
                    <a href="#">ipsum dolor</a><br>
                    <a href="#">dolor ipsum</a><br>
                    <a href="#">amet consectetur</a><br>
                    <a href="#">ipsum dolor sit</a><br>
                </div>
            </li>
            <li><i class="fa fa-envelope fa-fw"></i><a data-toggle="collapse" href="#contact-us"> Contact us</a>
                <div class="collapse" id="contact-us">
                    <a href="#">Lorem ipsum</a><br>
                    <a href="#">ipsum dolor</a><br>
                    <a href="#">dolor ipsum</a><br>
                    <a href="#">amet consectetur</a><br>
                    <a href="#">ipsum dolor sit</a><br>
                </div>
            </li>
            <li><i class="fa fa-users fa-fw"></i><a data-toggle="collapse" href="#our-team"> Our team</a>
                <div class="collapse" id="our-team">
                    <a href="#">Belques Darwish</a><br>
                    <a href="#">Kholod Aljalal</a><br>
                    <a href="#">Mohammed Alhumaidi</a><br>
                    <a href="#">Refat Alwajeeh</a><br>
                    <a href="#">Somia Alsaidi</a><br>
                </div>
            </li>
            <li><i class="fa fa-bolt fa-fw"></i><a data-toggle="collapse" href="#test"> Testimonials</a>
                <div class="collapse" id="test">
                    <a href="#">Lorem ipsum</a><br>
                    <a href="#">ipsum dolor</a><br>
                    <a href="#">dolor ipsum</a><br>
                    <a href="#">amet consectetur</a><br>
                    <a href="#">ipsum dolor sit</a><br>
                </div>
            </li>
            <p>Example:</p>
            <li><i class="fa fa-envelope-open-o fa-fw"></i><a href="#"> Messages <span class="num dang">56</span></a></li>
            <li><i class="fa fa-wrench fa-fw"></i><a data-toggle="collapse" href="#setting"> Settings <span class="num prim">6</span></a>
                <div class="collapse" id="setting">
                    <a href="#">Lorem ipsum</a><br>
                    <a href="#">ipsum dolor</a><br>
                    <a href="#">dolor ipsum</a><br>
                    <a href="#">amet consectetur</a><br>
                    <a href="#">ipsum dolor sit</a><br>
                </div>
            </li>
            <li><i class="fa fa-laptop fa-fw"></i><a href="#"> About UI &amp; UX <span class="num succ">43</span></a></li>
            <li><i class="fa fa-comments-o fa-fw"></i><a href="#"> Something else</a></li>
        </ul>
    </aside>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/js/fontawesome.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="/layout/js/jquery.validate.js"></script>
    <script src="/layout/js/backend.js"></script>
    <script src="/layout/js/main.js"></script>
    <script src="/layout/js/script.js"></script>