<?php
include "side_bar.phtml";
?>


<html>
<head>

    <style>
        .ex{
            color: #ffd700;
            font-size: 19px;
        }

        .w{
            color: #efefeb;
            font-size: 19px;
        }
    </style>



    <link href="/media/css/jquery.dataTables.min.css" rel="stylesheet">



</head>
<body>


<h1 class="text-center"> Manage User Exams</h1>
<br>

<div class="container-fluid">
    <div class="table-responsive">

        <table id="myTable" class="main-table text-center table table-bordered">
            <thead style="background-color: #44b7b9">
            <tr style="color: white">
                <th>#</th>
                <th>Name</th>
                <th>Total Mark</th>
                <th>pass Mark</th>
                <th>exam Result</th>
                <th>Start Time</th>
                <th>Finish Time</th>
                <th>Control</th>
            </tr>

            </thead>
            <tbody>
            <tr>
                <?php
                if (array_key_exists('Exams', $this->view_data)) {

                    $table = '';

                    foreach ($this->view_data['Exams'] as $exams) {


                        $table .= '<tr >';
                        $table .= ' <td >' . $exams["user_exam_id"] . '</td>';
                        $table .= ' <td>' . $exams["user_name"] . '</td>';
                        $table .= ' <td>' . $exams["exam_total_mark"] . '</td>';
                        $table .= ' <td >' . $exams["exam_pass_mark"] . '</td>';
                        $table .= ' <td>' . $exams["user_exam_result"] . '</td>';
                        $table .= ' <td>' . $exams["user_exam_date"] . '</td>';
                        $table .= ' <td>' . $exams["user_exam_finish_time"] . '</td>';


                        $table.=" <td>";
//

                        if ($exams["user_exam_result"] >= 90) {
                            $table .= '<i class=" ex fa fa-star"></i><i class=" ex fa fa-star"></i><i class=" ex fa fa-star"></i><i class=" ex fa fa-star"><i class=" ex fa fa-star">
 </td>';

                        }
                        elseif ($exams["user_exam_result"] >70 && $exams["user_exam_result"]<90) {
                            $table .= '<i class=" ex fa fa-star"></i><i class=" ex fa fa-star"></i><i class=" ex fa fa-star"></i><i class=" ex fa fa-star"><i class=" w fa fa-star">
</a>';
                        }
                        elseif ($exams["user_exam_result"] >65 && $exams["user_exam_result"]<80) {
                            $table .= '<i class=" ex fa fa-star"></i><i class=" ex fa fa-star"></i><i class=" ex fa fa-star"></i><i class=" w fa fa-star"><i class=" w fa fa-star">
</a>';
                        }
                        elseif ($exams["user_exam_result"] >50 && $exams["user_exam_result"]<65) {
                            $table .= '<i class=" ex fa fa-star"></i><i class=" ex fa fa-star"></i><i class=" w fa fa-star"></i><i class=" w fa fa-star"><i class=" w fa fa-star">
</a>';
                        }
                        elseif ($exams["user_exam_result"] <=50) {
                            $table .= '<i class=" ex fa fa-star"></i><i class=" w fa fa-star"></i><i class=" w fa fa-star"></i><i class=" w fa fa-star"><i class=" w fa fa-star">
</a>';
                        }

                        $table.="</td>";
                        $table.="</tr>";

                    }

                    echo $table;
                }
                ?>



            </tr>
            </tbody>

        </table>
    </div>
</div>

































<script src="/media/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function(){
        $("#myTable").dataTable();
    });

</script>


</body>
</html>

